/*
 * Copyright (c) 2026 WeebLabs
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Multi-instance I2S audio output library for RP2040/RP2350.
 *
 * Architecture mirrors pico_audio_spdif_multi: instance-based API, shared
 * DMA IRQ handler with reference-counted enable/disable, per-PIO-block
 * program caching, and synchronized multi-instance start.
 *
 * Key differences from SPDIF:
 *   - PIO program: 8-instruction I2S master (vs 4-instruction SPDIF NRZI)
 *   - Consumer stride: 8 bytes/sample (2 × int32) vs 16 bytes (2 × subframe)
 *   - DMA words per sample: 2 (vs 4 for SPDIF)
 *   - Encoding: simple left-shift by 8 (vs NRZI lookup table)
 *   - No preambles, channel status, or block structure
 *   - BCK/LRCLK shared across instances (side-set), data pin independent
 *   - Includes MCK generator on a separate PIO SM
 */

// Per-block producer/consumer path; must stay in RAM under XIP builds
// on both platforms (reached via connection function pointers).
#define I2S_TIME_CRITICAL __attribute__((noinline, section(".time_critical")))

#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdlib.h>
#include "pico/audio_i2s_multi.h"
#include "audio_i2s_clkout.pio.h"
#include "audio_i2s_dataout.pio.h"
#include "audio_i2s_dataout_extclk.pio.h"
// MCK is no longer PIO-driven (audio_mck.pio is gone) — see the MCK section
// below for the CLK_GPOUTn-based replacement.
#include "hardware/pio.h"
#include "hardware/gpio.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/clocks.h"   // CLK_GPOUTn config + clock_gpio_init_int_frac8()
#include "hardware/sync.h"

#ifndef container_of
#define container_of(ptr, type, member) \
    ((type *)((char *)(ptr) - offsetof(type, member)))
#endif

// ---------------------------------------------------------------------------
// Global shared state
// ---------------------------------------------------------------------------

// PIO program offsets per PIO block — loaded once per block, persist forever
static int i2s_pio_program_offset[3] = {-1, -1, -1};          // Master program
static int i2s_slave_pio_program_offset[3] = {-1, -1, -1};    // Slave program

// External-clock slave program: BCK/LRCLK GPIO numbers are patched into its
// `wait gpio` instructions at load time (the clock pins are runtime config),
// so unlike the two programs above it must be reloaded if the pin changes.
#define I2S_EXTCLK_PROG_LEN \
    (sizeof(audio_i2s_dataout_extclk_program_instructions) / sizeof(uint16_t))
static int i2s_extclk_pio_program_offset[3] = {-1, -1, -1};
static uint8_t i2s_extclk_patched_bck[3] = {0xFF, 0xFF, 0xFF};
static uint16_t i2s_extclk_prog_ram[I2S_EXTCLK_PROG_LEN];
static struct pio_program i2s_extclk_prog = {
    .instructions = i2s_extclk_prog_ram,
    .length = (uint8_t)I2S_EXTCLK_PROG_LEN,
    .origin = -1,
};

// Which registered I2S instance index is the clock master (-1 = none).
// Only the master SM runs the master PIO program (side-set drives BCK/LRCLK).
// All other I2S SMs run the slave program (data-only, no clock output).
static int8_t i2s_clock_master_index = -1;

// Instance registry (starvation getters, group ops, master election)
static audio_i2s_instance_t *i2s_instances[PICO_AUDIO_I2S_MAX_INSTANCES];
static uint i2s_instance_count = 0;

// Ring geometry (see the S/PDIF library's "Ring output model" comment; the
// I2S ring is the same design with 2 words/frame and pad-pattern silence).
// Non-zero padding in the low 8 bits of every 32-bit wire word so a DAC's
// zero-detect mute never latches (full rationale at the encode section).
#define I2S_PAD_PATTERN   0x01

#define I2S_RING_FRAMES   PICO_AUDIO_I2S_RING_FRAMES
#define I2S_RING_MASK     (I2S_RING_FRAMES - 1u)
#define I2S_RING_WORDS    (I2S_RING_FRAMES * 2u)
#define I2S_RING_BYTES    PICO_AUDIO_I2S_RING_BYTES
#define I2S_WRITABLE_FRAMES (I2S_RING_FRAMES - PICO_AUDIO_I2S_ERASE_AHEAD)
_Static_assert((I2S_RING_FRAMES & (I2S_RING_FRAMES - 1)) == 0,
               "I2S ring frame count must be a power of two");

#if !PICO_RP2350
// Reload source word for the RP2040 free-running pair. Deliberately
// non-const: the DMA reads it from RAM during flash blackout windows
// where an XIP fetch would stall the ring.
static uint32_t i2s_ring_words_const = I2S_RING_WORDS;
#endif

// ---------------------------------------------------------------------------
// MCK generator state
// ---------------------------------------------------------------------------
//
// MCK is generated by one of the four hardware CLK_GPOUTn clock outputs.
// No PIO state machine is consumed — we hand the GPIO directly to the
// chip's clock peripheral and let it divide clk_sys down to the desired
// MCK frequency.  See the MCK generator functions further below for the
// divider derivation; the in-line comment block there is the canonical
// reference.

static uint8_t  mck_pin_current = 0xFFu;   // 0xFF = uninitialised; setup() seeds.
static bool     mck_running     = false;   // true ⇔ pad mux routed to clk_gpoutN
                                           // for mck_pin_current AND a divider
                                           // has been programmed.  False on boot.
static uint32_t mck_div_24_8    = 0u;      // Last computed 24.8 fixed-point
                                           // divider.  Zero ≡ "never set" — an
                                           // enable in this state is refused.

// ---------------------------------------------------------------------------
// Ring accounting (same model as the S/PDIF library)
// ---------------------------------------------------------------------------

I2S_TIME_CRITICAL
uint32_t audio_i2s_ring_consumed_words(audio_i2s_instance_t *inst) {
    uint32_t save = save_and_disable_interrupts();
    uint32_t addr = dma_channel_hw_addr(inst->dma_channel)->read_addr;
    uint32_t delta = (addr - inst->last_read_addr) & (I2S_RING_BYTES - 1u);
    inst->last_read_addr = addr;
    inst->consumed_words += delta / 4u;
    uint32_t out = inst->consumed_words;
    restore_interrupts(save);
    return out;
}

I2S_TIME_CRITICAL
uint32_t audio_i2s_ring_fill_frames(audio_i2s_instance_t *inst) {
    return inst->wr_frames - audio_i2s_ring_consumed_words(inst) / 2u;
}

void audio_i2s_ring_reset(audio_i2s_instance_t *inst) {
    inst->wr_frames = 0;
    inst->erased_frames = 0;
    inst->consumed_words = 0;
    inst->last_read_addr = (uint32_t)(uintptr_t)inst->ring;
    inst->snap_produced_frames = 0;
    inst->snap_consumed_frames = 0;
    // Re-anchor the HARDWARE read pointer too: the abort left it frozen
    // mid-ring, and any consumed/fill read before the next arm would
    // otherwise count a bogus base-to-stale delta into consumed_words,
    // skewing this slot's accounting (and its re-arm offset) against the
    // others. DMA is stopped here per the contract, so the write is safe.
    dma_channel_set_read_addr(inst->dma_channel, inst->ring, false);
}

I2S_TIME_CRITICAL
void audio_i2s_ring_skip(audio_i2s_instance_t *inst, uint32_t frames) {
    inst->underrun_frames += frames;
    inst->wr_frames += frames;
    // Restamp silence through the new margin (see the S/PDIF twin).
    uint32_t target = inst->wr_frames + PICO_AUDIO_I2S_ERASE_AHEAD;
    uint32_t e = inst->erased_frames;
    if ((int32_t)(target - e) > (int32_t)I2S_RING_FRAMES) e = target - I2S_RING_FRAMES;
    while ((int32_t)(target - e) > 0) {
        int32_t *dst = &inst->ring[(e & I2S_RING_MASK) * 2u];
        dst[0] = (int32_t)I2S_PAD_PATTERN;
        dst[1] = (int32_t)I2S_PAD_PATTERN;
        e++;
    }
    inst->erased_frames = e;
}

// Silence pump; see the S/PDIF twin for the contract.
I2S_TIME_CRITICAL
void audio_i2s_ring_silence_pump(audio_i2s_instance_t *inst, uint32_t max_frames) {
    uint32_t consumed = audio_i2s_ring_consumed_words(inst) / 2u;
    uint32_t target = consumed + I2S_RING_FRAMES;
    uint32_t e = inst->erased_frames;
    if ((int32_t)(e - inst->wr_frames) < 0) e = inst->wr_frames;
    int32_t need = (int32_t)(target - e);
    if (need <= 0) return;
    uint32_t n = ((uint32_t)need > max_frames) ? max_frames : (uint32_t)need;
    while (n--) {
        int32_t *dst = &inst->ring[(e & I2S_RING_MASK) * 2u];
        dst[0] = (int32_t)I2S_PAD_PATTERN;
        dst[1] = (int32_t)I2S_PAD_PATTERN;
        e++;
    }
    inst->erased_frames = e;
}

I2S_TIME_CRITICAL
void audio_i2s_ring_write_s32(audio_i2s_instance_t *inst,
                              const int32_t *lr, uint32_t frames) {
    uint32_t consumed = audio_i2s_ring_consumed_words(inst) / 2u;
    uint32_t fill = inst->wr_frames - consumed;

    // Unsigned compare also covers reader-overtook-writer: writable = 0,
    // block dropped and counted; the DSPi give path re-anchors via skip().
    uint32_t writable = (fill < I2S_WRITABLE_FRAMES) ? (I2S_WRITABLE_FRAMES - fill) : 0;
    if (frames > writable) {
        inst->drop_frames += frames - writable;
        frames = writable;
    }

    uint32_t w = inst->wr_frames;
    for (uint32_t i = 0; i < frames; i++) {
        int32_t *dst = &inst->ring[(w & I2S_RING_MASK) * 2u];
        // 24-bit audio at MSB for I2S MSB-first output; pad pattern keeps
        // 32-bit DAC zero-detect from latching on silence.
        dst[0] = (lr[i * 2u]      << 8) | I2S_PAD_PATTERN;
        dst[1] = (lr[i * 2u + 1u] << 8) | I2S_PAD_PATTERN;
        w++;
    }
    inst->wr_frames = w;

    uint32_t e = inst->erased_frames;
    if (e < w) e = w;
    uint32_t target = w + PICO_AUDIO_I2S_ERASE_AHEAD;
    while (e < target) {
        int32_t *dst = &inst->ring[(e & I2S_RING_MASK) * 2u];
        dst[0] = (int32_t)I2S_PAD_PATTERN;
        dst[1] = (int32_t)I2S_PAD_PATTERN;
        e++;
    }
    inst->erased_frames = e;

    inst->snap_produced_frames = w;
    inst->snap_consumed_frames = consumed;
}

// ---------------------------------------------------------------------------
// Free-running DMA arm/stop
// ---------------------------------------------------------------------------

static void i2s_ring_dma_arm(audio_i2s_instance_t *inst) {
    pio_sm_clear_fifos(inst->pio, inst->pio_sm);

    uint32_t offset = (inst->consumed_words * 4u) & (I2S_RING_BYTES - 1u);
    uint8_t *start = (uint8_t *)inst->ring + offset;
    // Keep the unwrap anchor exactly in step with the address programmed
    // below so the first consumed read after (re)arm sees a zero delta.
    inst->last_read_addr = (uint32_t)(uintptr_t)start;

    dma_channel_config c = dma_channel_get_default_config(inst->dma_channel);
    channel_config_set_transfer_data_size(&c, DMA_SIZE_32);
    channel_config_set_read_increment(&c, true);
    channel_config_set_write_increment(&c, false);
    channel_config_set_ring(&c, false, __builtin_ctz(I2S_RING_BYTES));
    channel_config_set_dreq(&c, pio_get_dreq(inst->pio, inst->pio_sm, true));
    channel_config_set_high_priority(&c, true);

#if PICO_RP2350
    dma_channel_set_config(inst->dma_channel, &c, false);
    dma_channel_set_write_addr(inst->dma_channel, &inst->pio->txf[inst->pio_sm], false);
    dma_channel_set_read_addr(inst->dma_channel, start, false);
    dma_channel_set_trans_count(inst->dma_channel,
                                dma_encode_endless_transfer_count(), true);
#else
    dma_channel_config r = dma_channel_get_default_config(inst->dma_reload_channel);
    channel_config_set_transfer_data_size(&r, DMA_SIZE_32);
    channel_config_set_read_increment(&r, false);
    channel_config_set_write_increment(&r, false);
    dma_channel_configure(inst->dma_reload_channel, &r,
                          &dma_hw->ch[inst->dma_channel].al1_transfer_count_trig,
                          &i2s_ring_words_const, 1, false);

    channel_config_set_chain_to(&c, inst->dma_reload_channel);
    dma_channel_set_config(inst->dma_channel, &c, false);
    dma_channel_set_write_addr(inst->dma_channel, &inst->pio->txf[inst->pio_sm], false);
    dma_channel_set_read_addr(inst->dma_channel, start, false);
    dma_channel_set_trans_count(inst->dma_channel, I2S_RING_WORDS, true);
#endif
}

static void i2s_ring_dma_stop(audio_i2s_instance_t *inst) {
#if !PICO_RP2350
    // Break the chain loop before aborting so the reload cannot re-arm the
    // data channel mid-abort.
    hw_write_masked(&dma_hw->ch[inst->dma_channel].al1_ctrl,
                    (uint32_t)inst->dma_channel << DMA_CH0_CTRL_TRIG_CHAIN_TO_LSB,
                    DMA_CH0_CTRL_TRIG_CHAIN_TO_BITS);
    dma_hw->abort = (1u << inst->dma_channel) | (1u << inst->dma_reload_channel);
    while ((dma_hw->ch[inst->dma_channel].ctrl_trig & DMA_CH0_CTRL_TRIG_BUSY_BITS) ||
           (dma_hw->ch[inst->dma_reload_channel].ctrl_trig & DMA_CH0_CTRL_TRIG_BUSY_BITS))
        tight_loop_contents();
#else
    dma_channel_abort(inst->dma_channel);
    // Leave ENDLESS mode (mirrors adat_input_stop).
    dma_channel_hw_addr(inst->dma_channel)->transfer_count = 0;
#endif
}

// ---------------------------------------------------------------------------
// PIO block index helper
// ---------------------------------------------------------------------------

static PIO i2s_pio_block_from_index(uint8_t idx) {
    switch (idx) {
        case 0: return pio0;
        case 1: return pio1;
#if NUM_PIOS > 2
        case 2: return pio2;
#endif
        default: panic("Invalid PIO index %d", idx);
    }
}

// ---------------------------------------------------------------------------
// Clock divider calculation
// ---------------------------------------------------------------------------

// I2S timing:
//   Each audio bit takes 2 PIO clocks (out + jmp instruction pair).
//   32 bits/channel × 2 channels = 64 bits/frame × 2 clocks/bit = 128 PIO
//   clocks per stereo sample.
//
//   PIO_clk = sample_freq × 128
//
//   divider (24.8 fixed-point) = sys_clk × 256 / PIO_clk
//                               = sys_clk × 256 / (sample_freq × 128)
//                               = sys_clk × 2 / sample_freq
//
//   At 307.2 MHz / 48 kHz: divider = 12800 → integer 50, fractional 0
//   (zero PIO clock jitter)

// Patch the 5-bit GPIO index field of a `wait gpio` instruction.
static inline uint16_t i2s_patch_wait_gpio(uint16_t instr, uint8_t pin) {
    return (uint16_t)((instr & ~0x1Fu) | (pin & 0x1Fu));
}

// Remove the external-clock slave program from a PIO block if loaded.  Also
// called from the master/dataout setup paths: the checked extclk program
// (26 instructions) cannot share the 32-slot block with clkout (8) +
// dataout (8) + SPDIF (4), so the two clocking modes evict each other's
// programs.  Safe because clocking mode is global: a mode rebuild tears
// down every I2S SM before any setup path runs.
static void i2s_extclk_evict_program(PIO pio) {
    uint idx = pio_get_index(pio);
    if (i2s_extclk_pio_program_offset[idx] < 0) return;
    for (uint i = 0; i < i2s_instance_count; i++) {
        assert(!(i2s_instances[i]->external_clock &&
                 i2s_instances[i]->pio == pio && i2s_instances[i]->enabled));
    }
    pio_remove_program(pio, &i2s_extclk_prog,
                       (uint)i2s_extclk_pio_program_offset[idx]);
    i2s_extclk_pio_program_offset[idx] = -1;
    i2s_extclk_patched_bck[idx] = 0xFF;
}

// (Re)load the external-clock slave program on a PIO block with the current
// BCK/LRCLK GPIOs patched into its wait instructions.  Reloads (remove + add)
// only when the patched pin differs; no extclk SM on the block may be enabled
// during a reload (every enable path re-jumps SMs to the entry point, so a
// relocated offset cannot strand a disabled SM's PC).
//
// Patching per audio_i2s_dataout_extclk.pio: the program is authored with
// placeholder GPIO indices (0 = BCK, 1 = LRCLK); every WAIT-source-GPIO
// instruction gets its 5-bit index rewritten to the runtime pin.
static uint i2s_extclk_load_program(PIO pio, uint8_t bck_pin) {
    uint idx = pio_get_index(pio);
    if (i2s_extclk_pio_program_offset[idx] >= 0) {
        if (i2s_extclk_patched_bck[idx] == bck_pin)
            return (uint)i2s_extclk_pio_program_offset[idx];
        // Load-bearing invariant: reload only with every extclk SM disabled.
        i2s_extclk_evict_program(pio);
    }

    // Make room: evict the master-clocking programs (see i2s_extclk_evict_program).
    if (i2s_pio_program_offset[idx] >= 0) {
        pio_remove_program(pio, &audio_i2s_clkout_program,
                           (uint)i2s_pio_program_offset[idx]);
        i2s_pio_program_offset[idx] = -1;
    }
    if (i2s_slave_pio_program_offset[idx] >= 0) {
        pio_remove_program(pio, &audio_i2s_dataout_program,
                           (uint)i2s_slave_pio_program_offset[idx]);
        i2s_slave_pio_program_offset[idx] = -1;
    }

    memcpy(i2s_extclk_prog_ram, audio_i2s_dataout_extclk_program_instructions,
           sizeof(i2s_extclk_prog_ram));
    for (uint i = 0; i < I2S_EXTCLK_PROG_LEN; i++) {
        uint16_t instr = i2s_extclk_prog_ram[i];
        if ((instr >> 13) != 0x1u) continue;         // not a WAIT
        if (((instr >> 5) & 0x3u) != 0u) continue;   // WAIT source not GPIO
        uint8_t pin = (instr & 0x1Fu) ? (uint8_t)(bck_pin + 1) : bck_pin;
        i2s_extclk_prog_ram[i] = i2s_patch_wait_gpio(instr, pin);
    }
    i2s_extclk_patched_bck[idx] = bck_pin;
    i2s_extclk_pio_program_offset[idx] = pio_add_program(pio, &i2s_extclk_prog);
    return (uint)i2s_extclk_pio_program_offset[idx];
}

// Compute the I2S clock divider in 24.8 fixed-point for a given sample rate.
static uint32_t i2s_compute_divider(uint32_t sample_freq) {
    uint32_t system_clock_frequency = clock_get_hz(clk_sys);
    assert(system_clock_frequency < 0x40000000);

    // divider = exactly 2x the SPDIF TX divider ceil(sys_clk / sample_freq),
    // NOT ceil(sys_clk * 2 / sample_freq): the two can differ by one LSB
    // (e.g. 176.4 kHz), and a divider RATIO error is a rate offset between
    // output types that no common sys_clk trim (soft VCXO) can correct.
    // Identical at every currently supported rate.
    uint32_t divider = 2u * (system_clock_frequency / sample_freq +
                             (system_clock_frequency % sample_freq != 0));
    assert(divider < 0x1000000);
    return divider;
}

// Update clock divider for a single instance AND all other I2S instances on
// the same PIO block.  All I2S SMs must run at the same rate because they
// share BCK/LRCLK timing from the master.  External-clock slave SMs are
// wait-driven at divider 1.0; their dividers are never touched, but freq
// is still tracked for bookkeeping.
static void i2s_update_pio_frequency(audio_i2s_instance_t *inst, uint32_t sample_freq) {
    uint32_t divider = i2s_compute_divider(sample_freq);

    printf("I2S clock divider 0x%x/256 (%u.%u) for %d Hz (all %d instances)\n",
           (uint)divider, (uint)(divider >> 8), (uint)(divider & 0xff),
           (int)sample_freq, i2s_instance_count);

    // Apply to ALL registered I2S instances on the same PIO block
    for (uint i = 0; i < i2s_instance_count; i++) {
        audio_i2s_instance_t *other = i2s_instances[i];
        if (other && other->pio == inst->pio) {
            if (!other->external_clock) {
                pio_sm_set_clkdiv_int_frac(other->pio, other->pio_sm,
                                            divider >> 8u, divider & 0xffu);
            }
            other->freq = sample_freq;
        }
    }
    // Also update the triggering instance (it may not be registered yet during setup)
    if (!inst->external_clock) {
        pio_sm_set_clkdiv_int_frac(inst->pio, inst->pio_sm,
                                    divider >> 8u, divider & 0xffu);
    }
    inst->freq = sample_freq;
}

// ---------------------------------------------------------------------------
// Connection callbacks
// ---------------------------------------------------------------------------

// (Consumer-take wrapper removed: the ring path has no consumer pool; the
// lazy rate follow lives in the producer-give wrapper.)

// ---------------------------------------------------------------------------
// I2S sample encoding: left-justify 24-bit audio into 32-bit I2S frames
//
// Producer buffer: interleaved int32_t L/R pairs, 24-bit audio in bits [23:0]
// Consumer buffer: interleaved int32_t L/R pairs, 24-bit audio in bits [31:8]
//
// The PIO shifts MSB-first, so audio must be in the upper 24 bits.
// The lower 8 bits carry an anti-zero-detect-mute marker so DACs configured
// for 32-bit input never see an all-zero word — defeats auto-mute clicks
// without perturbing the 24-bit audio at [31:8].  See I2S_PAD_PATTERN.
//
// This is dramatically simpler than SPDIF BMC encoding — just a left-shift.
// ---------------------------------------------------------------------------

// Anti-zero-detect-mute padding written into the bottom 8 bits of every I2S
// frame.  The audio data at [31:8] is bit-perfect 24-bit; this byte sits in
// the I2S "padding" region that 24-bit DACs ignore and 32-bit DACs evaluate
// for zero-detect.  Constant 0x01 keeps every wire word non-zero with the
// minimum possible disturbance — a single LSB at bit 0 of the 32-bit frame.
// 24-bit-configured DACs are not helped by this trick (they can't see [7:0]);
// for them the muted-output click problem must be addressed elsewhere.
// (I2S_PAD_PATTERN itself is defined with the ring geometry near the top.)

// The shared per-slot consumer pool sizes its data blocks to the S/PDIF stride;
// the I2S stride must fit within that. Pin it to the real frame size here.
_Static_assert(PICO_AUDIO_I2S_CONSUMER_FRAME_BYTES == 2 * sizeof(int32_t),
               "PICO_AUDIO_I2S_CONSUMER_FRAME_BYTES must equal the stereo I2S frame stride");

// I2S producer-give callback.
//
// Follows the same pattern as SPDIF's stereo_to_spdif_producer_give_s32():
//   1. Take a free consumer buffer (blocking — waits for DMA to return one)
//   2. Convert producer samples into consumer format
//   3. Return producer buffer to free list via queue_free_audio_buffer()
//      (NOT give_audio_buffer, which would re-trigger this callback → recursion)
//   4. Give consumer buffer to prepared list for DMA pickup
//
I2S_TIME_CRITICAL
static void i2s_wrap_producer_give(audio_connection_t *connection, audio_buffer_t *buffer) {
    struct producer_pool_blocking_give_connection *pbc =
        (struct producer_pool_blocking_give_connection *)connection;
    audio_i2s_instance_t *inst =
        container_of(pbc, audio_i2s_instance_t, connection);

    // Lazy rate follow (replaces the old consumer-take hook). External-clock
    // SMs run at divider 1.0 and are skipped inside the update.
    if (connection->producer_pool->format->sample_freq != inst->freq) {
        i2s_update_pio_frequency(inst, connection->producer_pool->format->sample_freq);
    }

    audio_i2s_ring_write_s32(inst, (const int32_t *)buffer->buffer->bytes,
                             buffer->sample_count);
    queue_free_audio_buffer(connection->producer_pool, buffer);
}

// ---------------------------------------------------------------------------
// audio_i2s_setup
// ---------------------------------------------------------------------------

const audio_format_t *audio_i2s_setup(audio_i2s_instance_t *inst,
                                       const audio_format_t *intended_audio_format,
                                       const audio_i2s_config_t *config) {
    assert(i2s_instance_count < PICO_AUDIO_I2S_MAX_INSTANCES);

    // Store hardware config into instance
    inst->pio = i2s_pio_block_from_index(config->pio);
    inst->pio_sm = config->pio_sm;
    inst->dma_channel = config->dma_channel;
    inst->dma_irq = config->dma_irq;
    inst->data_pin = config->data_pin;
    inst->clock_pin_base = config->clock_pin_base;
    inst->external_clock = config->external_clock;
    inst->clock_master = config->external_clock ? false : config->clock_master;
    inst->dma_reload_channel = config->dma_reload_channel;
    inst->freq = 0;
    inst->enabled = false;
    // Stable slot identity for stats and the shared slot ring.
    inst->instance_index = config->dma_channel;
    assert(config->ring_base != NULL);
    assert(((uintptr_t)config->ring_base & (I2S_RING_BYTES - 1u)) == 0);
    inst->ring = (int32_t *)config->ring_base;
    inst->underrun_frames = 0;
    inst->drop_frames = 0;
    audio_i2s_ring_reset(inst);

    // This instance struct may be reused across output-type switches.
    // Clear carry-over connection state so a stale staging pointer from a
    // previous lifetime cannot be consumed after reconnect.
    memset(&inst->connection, 0, sizeof(inst->connection));

    // Assert all instances share the same DMA IRQ line
    if (i2s_instance_count > 0) {
        assert(inst->dma_irq == i2s_instances[0]->dma_irq);
    }

    // GPIO init for data pin (always)
    pio_gpio_init(inst->pio, config->data_pin);

    // Claim SM
    pio_sm_claim(inst->pio, inst->pio_sm);

    if (inst->external_clock) {
        // ---- EXTERNAL-CLOCK SLAVE: waits on BCK/LRCLK driven by an
        // external master; both clock pads are inputs, nothing on-chip
        // drives them ----

        // Make the clock pads readable: SIO function clears the RP2350 pad
        // isolation latch, direction stays input.  Idempotent with the I2S
        // clock-slave input path, which shares the same pads.
        gpio_init(config->clock_pin_base);
        gpio_set_input_enabled(config->clock_pin_base, true);
        gpio_init(config->clock_pin_base + 1);
        gpio_set_input_enabled(config->clock_pin_base + 1, true);

        uint offset = i2s_extclk_load_program(inst->pio, config->clock_pin_base);
        audio_i2s_dataout_extclk_program_init(inst->pio, inst->pio_sm, offset,
                                              config->data_pin, config->clock_pin_base);

        printf("I2S setup: SM%d as EXT-CLK SLAVE (data GPIO %d, BCK GPIO %d)\n",
               inst->pio_sm, inst->data_pin, inst->clock_pin_base);
    } else if (config->clock_master) {
        // ---- MASTER: drives BCK/LRCLK via side-set ----

        // GPIO init for clock pins (master only)
        pio_gpio_init(inst->pio, config->clock_pin_base);
        pio_gpio_init(inst->pio, config->clock_pin_base + 1);

        // Load master PIO program once per PIO block (evicting the extclk
        // program first if a slave-mode session left it loaded: the two
        // clocking modes cannot share the block's instruction memory)
        if (i2s_pio_program_offset[config->pio] < 0) {
            i2s_extclk_evict_program(inst->pio);
            i2s_pio_program_offset[config->pio] =
                pio_add_program(inst->pio, &audio_i2s_clkout_program);
        }
        uint offset = (uint)i2s_pio_program_offset[config->pio];

        // Initialize with master program (side-set drives BCK/LRCLK)
        audio_i2s_clkout_program_init(inst->pio, inst->pio_sm, offset,
                                   config->data_pin, config->clock_pin_base);

        // Track this instance as the clock master
        i2s_clock_master_index = (int8_t)i2s_instance_count;  // Will be registered below

        printf("I2S setup: SM%d as MASTER (data GPIO %d, BCK GPIO %d)\n",
               inst->pio_sm, inst->data_pin, inst->clock_pin_base);
    } else {
        // ---- SLAVE: data-only, no clock output ----

        // Do NOT init BCK/LRCLK pins — master owns them

        // Load slave PIO program once per PIO block (evicting the extclk
        // program first if a slave-mode session left it loaded)
        if (i2s_slave_pio_program_offset[config->pio] < 0) {
            i2s_extclk_evict_program(inst->pio);
            i2s_slave_pio_program_offset[config->pio] =
                pio_add_program(inst->pio, &audio_i2s_dataout_program);
        }
        uint offset = (uint)i2s_slave_pio_program_offset[config->pio];

        // Initialize with slave program (no side-set, data pin only)
        audio_i2s_dataout_program_init(inst->pio, inst->pio_sm, offset,
                                         config->data_pin);

        printf("I2S setup: SM%d as SLAVE (data GPIO %d)\n",
               inst->pio_sm, inst->data_pin);
    }

    inst->consumer_buffer_format.format = &inst->consumer_format;

    __mem_fence_release();

    // Claim DMA; configuration happens at each arm. Ensure no stale
    // completion latch or per-channel IRQ enable survives from a prior
    // pool-mode user of this channel.
    dma_channel_claim(inst->dma_channel);
#if !PICO_RP2350
    dma_channel_claim(inst->dma_reload_channel);
#endif
    dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, false);
    dma_irqn_acknowledge_channel(inst->dma_irq, inst->dma_channel);

    // Register instance.
    uint32_t save = save_and_disable_interrupts();
    i2s_instances[i2s_instance_count++] = inst;
    restore_interrupts(save);

    return intended_audio_format;
}

// ---------------------------------------------------------------------------
// audio_i2s_connect_extra
// ---------------------------------------------------------------------------

bool audio_i2s_connect_extra(audio_i2s_instance_t *inst,
                              audio_buffer_pool_t *producer,
                              bool buffer_on_give, audio_buffer_pool_t *consumer_pool,
                              audio_connection_t *connection) {
    printf("Connecting PIO I2S audio (SM%d, data GPIO %d, BCK GPIO %d)\n",
           inst->pio_sm, inst->data_pin, inst->clock_pin_base);

    assert(producer->format->format == AUDIO_BUFFER_FORMAT_PCM_S32);

    // Consumer format: raw PCM for I2S (2 × int32 per stereo sample)
    inst->consumer_format.format = AUDIO_BUFFER_FORMAT_PIO_I2S;
    inst->consumer_format.sample_freq = producer->format->sample_freq;
    inst->consumer_format.channel_count = 2;
    inst->consumer_buffer_format.format = &inst->consumer_format;
    inst->consumer_buffer_format.sample_stride = 2 * sizeof(int32_t);  // 8 bytes

    (void)buffer_on_give;
    (void)consumer_pool;   // ring path: the shared static pool is unused

    i2s_update_pio_frequency(inst, producer->format->sample_freq);

    __mem_fence_release();

    if (!connection) {
        printf("I2S stereo 24-bit at %d Hz (ring)\n", (int)producer->format->sample_freq);

        inst->connection.core.consumer_pool_take = NULL;
        inst->connection.core.consumer_pool_give = NULL;
        inst->connection.core.producer_pool_take = producer_pool_take_buffer_default;
        inst->connection.core.producer_pool_give = i2s_wrap_producer_give;
        connection = &inst->connection.core;
    }
    // Manual link: there is no consumer pool to complete a connection with.
    connection->producer_pool = producer;
    connection->consumer_pool = NULL;
    producer->connection = connection;
    return true;
}

// ---------------------------------------------------------------------------
// DMA transfer
// ---------------------------------------------------------------------------

// (Pool-mode DMA transfer starter and DMA IRQ handler removed: the ring
// path runs free-running DMA with zero IRQs; see i2s_ring_dma_arm/stop.)

// ---------------------------------------------------------------------------
// audio_i2s_set_enabled
// ---------------------------------------------------------------------------

void audio_i2s_set_enabled(audio_i2s_instance_t *inst, bool enabled) {
    if (enabled != inst->enabled) {
        if (enabled) {
            i2s_ring_dma_arm(inst);
            pio_sm_set_enabled(inst->pio, inst->pio_sm, true);
        } else {
            pio_sm_set_enabled(inst->pio, inst->pio_sm, false);
            i2s_ring_dma_stop(inst);
        }
        inst->enabled = enabled;
    }
}

// ---------------------------------------------------------------------------
// audio_i2s_change_data_pin
// ---------------------------------------------------------------------------

void audio_i2s_change_data_pin(audio_i2s_instance_t *inst, uint new_pin) {
    assert(!inst->enabled);

    i2s_ring_dma_stop(inst);

    // Release old data pin from PIO mux -> high-Z
    gpio_set_function(inst->data_pin, GPIO_FUNC_NULL);
    gpio_set_dir(inst->data_pin, GPIO_IN);

    // Claim new data pin for PIO
    pio_gpio_init(inst->pio, new_pin);

    // Reinitialize SM with new data pin using the correct program for role
    uint pio_idx = pio_get_index(inst->pio);
    if (inst->external_clock) {
        assert(i2s_extclk_pio_program_offset[pio_idx] >= 0);
        audio_i2s_dataout_extclk_program_init(inst->pio, inst->pio_sm,
                (uint)i2s_extclk_pio_program_offset[pio_idx], new_pin,
                inst->clock_pin_base);
    } else if (inst->clock_master) {
        assert(i2s_pio_program_offset[pio_idx] >= 0);
        uint offset = (uint)i2s_pio_program_offset[pio_idx];
        audio_i2s_clkout_program_init(inst->pio, inst->pio_sm, offset,
                                   new_pin, inst->clock_pin_base);
    } else {
        assert(i2s_slave_pio_program_offset[pio_idx] >= 0);
        uint offset = (uint)i2s_slave_pio_program_offset[pio_idx];
        audio_i2s_dataout_program_init(inst->pio, inst->pio_sm, offset, new_pin);
    }

    // Restore clock divider (pio_sm_init resets it to default)
    if (inst->freq != 0) {
        i2s_update_pio_frequency(inst, inst->freq);
    }

    // pio_sm_init() reset this SM's clock divider phase accumulator.
    // Restart ALL I2S SM dividers on this PIO block so they stay phase-aligned.
    // Without this, the re-inited SM's divider is at phase 0 while others are
    // at arbitrary phases — causing permanent bit-level misalignment.
    {
        uint32_t sm_mask = 0;
        for (uint i = 0; i < i2s_instance_count; i++) {
            if (i2s_instances[i]->pio == inst->pio)
                sm_mask |= (1u << i2s_instances[i]->pio_sm);
        }
        if (sm_mask)
            pio_clkdiv_restart_sm_mask(inst->pio, sm_mask);
    }

    inst->data_pin = new_pin;
}

// ---------------------------------------------------------------------------
// audio_i2s_enable_sync — synchronized start for multiple instances
// ---------------------------------------------------------------------------

// Prepare-only half of the synchronized start: SM rewind, IRQ refcounts, DMA
// priming and enabled-flag bookkeeping, WITHOUT starting the SMs.  Returns
// the SM mask for the (single, shared) PIO block; the caller performs the
// pio_enable_sm_mask_in_sync.  Lets a caller prime BOTH output types first
// and then start every slot in one mask write (the I2S clock-slave path
// gates that write on an external LRCLK edge).
uint32_t audio_i2s_enable_sync_prepare(audio_i2s_instance_t *instances[], uint count) {
    assert(count > 0 && count <= PICO_AUDIO_I2S_MAX_INSTANCES);

    // Rewind each SM to a known program entry state before synchronous start.
    // pio_enable_sm_mask_in_sync() aligns divider phase, but does not reset
    // instruction position or shift counters. Without this reset, previously
    // running SMs can resume at different bit positions and produce data/clock
    // misalignment (audible as white-noise-like corruption).
    for (uint i = 0; i < count; i++) {
        audio_i2s_instance_t *inst = instances[i];
        uint pio_idx = pio_get_index(inst->pio);
        uint entry_pc;

        if (inst->external_clock) {
            assert(i2s_extclk_pio_program_offset[pio_idx] >= 0);
            entry_pc = (uint)i2s_extclk_pio_program_offset[pio_idx] +
                       audio_i2s_dataout_extclk_offset_entry_point;
        } else if (inst->clock_master) {
            assert(i2s_pio_program_offset[pio_idx] >= 0);
            entry_pc = (uint)i2s_pio_program_offset[pio_idx] + audio_i2s_clkout_offset_entry_point;
        } else {
            assert(i2s_slave_pio_program_offset[pio_idx] >= 0);
            entry_pc = (uint)i2s_slave_pio_program_offset[pio_idx] + audio_i2s_dataout_offset_entry_point;
        }

        pio_sm_clear_fifos(inst->pio, inst->pio_sm);
        pio_sm_restart(inst->pio, inst->pio_sm);
        pio_sm_exec(inst->pio, inst->pio_sm, pio_encode_jmp(entry_pc));

        // A framing slip flagged before this restart is already being
        // handled (this restart IS the handling); a stale flag left set
        // would immediately re-trigger the slip watchdog after re-lock.
        if (inst->external_clock)
            pio_interrupt_clear(inst->pio, AUDIO_I2S_EXTCLK_SLIP_IRQ);
    }

    // Arm free-running DMA for all instances (pre-fills each PIO FIFO,
    // then stalls on DREQ until the synchronized SM start).
    for (uint i = 0; i < count; i++) {
        i2s_ring_dma_arm(instances[i]);
    }

    // All instances share one PIO block (asserted); build its SM mask
    uint32_t sm_mask = 0;
    for (uint i = 0; i < count; i++) {
        assert(instances[i]->pio == instances[0]->pio);
        sm_mask |= (1u << instances[i]->pio_sm);
    }

    for (uint i = 0; i < count; i++) {
        instances[i]->enabled = true;
    }
    return sm_mask;
}

void audio_i2s_enable_sync(audio_i2s_instance_t *instances[], uint count) {
    uint32_t sm_mask = audio_i2s_enable_sync_prepare(instances, count);

    // Disable interrupts briefly and start all SMs synchronously
    uint32_t save = save_and_disable_interrupts();
    pio_enable_sm_mask_in_sync(instances[0]->pio, sm_mask);
    restore_interrupts(save);
}

// Starvation API, unit change: counts are FRAMES of silence exposed to the
// wire (ring underrun accounting, always on).
void audio_i2s_set_starvation_monitoring(bool enabled) {
    (void)enabled;
}

void audio_i2s_reset_dma_starvations(void) {
    for (uint i = 0; i < i2s_instance_count; i++) {
        i2s_instances[i]->underrun_frames = 0;
        i2s_instances[i]->drop_frames = 0;
    }
}

uint32_t audio_i2s_get_dma_starvations(void) {
    uint32_t total = 0;
    for (uint i = 0; i < i2s_instance_count; i++) {
        total += i2s_instances[i]->underrun_frames;
    }
    return total;
}

uint32_t audio_i2s_get_dma_starvations_instance(uint index) {
    for (uint i = 0; i < i2s_instance_count; i++) {
        if (i2s_instances[i]->instance_index == index) {
            return i2s_instances[i]->underrun_frames;
        }
    }
    return 0;
}

// ---------------------------------------------------------------------------
// audio_i2s_teardown — full cleanup for output type switching
// ---------------------------------------------------------------------------

void audio_i2s_teardown(audio_i2s_instance_t *inst) {
    // Disable if still running
    if (inst->enabled) {
        audio_i2s_set_enabled(inst, false);
    } else {
        i2s_ring_dma_stop(inst);
    }

    // Break the producer connection link so accidental post-teardown give
    // paths fail fast.
    if (inst->connection.core.producer_pool &&
        inst->connection.core.producer_pool->connection == &inst->connection.core) {
        inst->connection.core.producer_pool->connection = NULL;
    }
    inst->connection.core.producer_pool_take = NULL;
    inst->connection.core.producer_pool_give = NULL;
    inst->connection.core.consumer_pool_take = NULL;
    inst->connection.core.consumer_pool_give = NULL;
    inst->connection.core.producer_pool = NULL;
    inst->connection.core.consumer_pool = NULL;

    // Release data pin
    gpio_set_function(inst->data_pin, GPIO_FUNC_NULL);
    gpio_set_dir(inst->data_pin, GPIO_IN);

    // Unclaim DMA channel(s) and PIO SM
    dma_channel_unclaim(inst->dma_channel);
#if !PICO_RP2350
    dma_channel_unclaim(inst->dma_reload_channel);
#endif
    pio_sm_unclaim(inst->pio, inst->pio_sm);

    // Remove from instance registry atomically against DMA IRQ iteration.
    bool was_master = inst->clock_master;
    uint32_t save = save_and_disable_interrupts();
    for (uint i = 0; i < i2s_instance_count; i++) {
        if (i2s_instances[i] == inst) {
            for (uint j = i; j < i2s_instance_count - 1; j++) {
                i2s_instances[j] = i2s_instances[j + 1];
            }
            i2s_instance_count--;
            break;
        }
    }

    // Master election bookkeeping
    if (was_master) {
        i2s_clock_master_index = -1;

        if (i2s_instance_count == 0) {
            // Last I2S instance removed — release BCK/LRCLK to high-Z
            gpio_set_function(inst->clock_pin_base, GPIO_FUNC_NULL);
            gpio_set_dir(inst->clock_pin_base, GPIO_IN);
            gpio_set_function(inst->clock_pin_base + 1, GPIO_FUNC_NULL);
            gpio_set_dir(inst->clock_pin_base + 1, GPIO_IN);
        }
        // If other instances remain, do NOT release BCK/LRCLK — the pins
        // hold their last driven level (no high-Z glitch). The caller is
        // responsible for promoting a slave to master and restarting in sync.
    }
    restore_interrupts(save);

    printf("I2S teardown: SM%d %s, data GPIO %d (instances remaining: %d)\n",
           inst->pio_sm, was_master ? "(was master)" : "(slave)",
           inst->data_pin, i2s_instance_count);
}

// ---------------------------------------------------------------------------
// Atomic frequency update for all I2S instances (called on sample rate change)
// ---------------------------------------------------------------------------

void audio_i2s_update_all_frequencies(uint32_t sample_freq) {
    if (i2s_instance_count == 0) return;

    uint32_t divider = i2s_compute_divider(sample_freq);

    // Update divider on ALL instances and build masks for restart.
    // all_sm_mask covers every registered SM for clkdiv phase reset.
    uint32_t all_sm_mask = 0;
    audio_i2s_instance_t *active[PICO_AUDIO_I2S_MAX_INSTANCES];
    uint active_count = 0;
    PIO pio = NULL;

    for (uint i = 0; i < i2s_instance_count; i++) {
        audio_i2s_instance_t *inst = i2s_instances[i];

        // Quiesce currently enabled instances before sync re-enable
        // (set_enabled(false) stops the SM and the free-running DMA).
        if (inst->enabled) {
            audio_i2s_set_enabled(inst, false);
            active[active_count++] = inst;
        }

        if (!inst->external_clock) {
            pio_sm_set_clkdiv_int_frac(inst->pio, inst->pio_sm,
                                        divider >> 8u, divider & 0xffu);
        }
        inst->freq = sample_freq;
        all_sm_mask |= (1u << inst->pio_sm);
        pio = inst->pio;
    }

    // Reset clkdiv phase for ALL SMs (including disabled ones) so they're
    // phase-aligned when later re-enabled. Without this, a disabled SM's
    // divider accumulator drifts and it starts misaligned.
    if (pio && all_sm_mask) {
        pio_clkdiv_restart_sm_mask(pio, all_sm_mask);
    }

    // Restart previously enabled SMs in sync
    if (active_count > 0 && pio) {
        audio_i2s_enable_sync(active, active_count);
    }

    printf("I2S rate change: all %d instances updated to %d Hz\n",
           i2s_instance_count, (int)sample_freq);
}

// ---------------------------------------------------------------------------
// Master election query
// ---------------------------------------------------------------------------

int8_t audio_i2s_get_clock_master_index(void) {
    return i2s_clock_master_index;
}

// ---------------------------------------------------------------------------
// External-clock framing-slip flag
// ---------------------------------------------------------------------------

// True if any external-clock I2S output SM flagged a framing slip since the
// last call (read-and-clear).  The flag is block-wide (PIO irq flag
// AUDIO_I2S_EXTCLK_SLIP_IRQ); no other program on the SPDIF/I2S TX block
// raises PIO irq flags, so a set flag is unambiguous.  Polled by the I2S
// clock-slave input's slip watchdog, which treats it like a clock loss.
bool __time_critical_func(audio_i2s_extclk_framing_slipped)(void) {
    bool slipped = false;
    for (uint8_t idx = 0; idx < 3; idx++) {
        if (i2s_extclk_pio_program_offset[idx] < 0) continue;
        PIO pio = i2s_pio_block_from_index(idx);
        if (pio_interrupt_get(pio, AUDIO_I2S_EXTCLK_SLIP_IRQ)) {
            pio_interrupt_clear(pio, AUDIO_I2S_EXTCLK_SLIP_IRQ);
            slipped = true;
        }
    }
    return slipped;
}

// ---------------------------------------------------------------------------
// MCK generator functions
// ---------------------------------------------------------------------------
//
// Lifecycle:
//
//   audio_i2s_mck_setup(pin)
//     ↓ (records pin; no hardware effect — boot is free of MCK power-on chirp)
//   audio_i2s_mck_update_frequency(Fs, mult)
//     ↓ (computes 24.8 divider; reloads it if running)
//   audio_i2s_mck_set_enabled(true)
//     ↓ (configures CLK_GPOUTn divider + AUXSRC; routes pad mux)
//   ...running...
//   audio_i2s_mck_set_enabled(false)
//     ↓ (disconnects pad mux; pin floats; generator left running internally)
//
// Glitchless rate change:
//   audio_i2s_mck_update_frequency() is idempotent and safe to call while
//   running.  clock_gpio_init_int_frac8() reloads the DIV register and
//   re-asserts the ENABLE bit without dropping the pin between cycles.
//
// SPDIF clock-domain servo:
//   audio_i2s_mck_set_divider(div_24_8) bypasses the (Fs × multiplier)
//   computation and writes a raw 24.8 divider — used by spdif_input.c to
//   apply ppm-level corrections from the resampler / clock servo.
//
// Reference table at sys_clk = 307.2 MHz:
//
//   Fs      Mult    MCK target      Divider 24.8                  Type
//   48k     128×    6.144  MHz      sys_clk × 256 / (48k × 128)   = 50.0    integer
//   48k     256×    12.288 MHz      sys_clk × 256 / (48k × 256)   = 25.0    integer
//   96k     128×    12.288 MHz      sys_clk × 256 / (96k × 128)   = 25.0    integer
//   96k     256×    24.576 MHz      sys_clk × 256 / (96k × 256)   = 12.5    fractional
//
// Only 96 kHz × 256× remains fractional.  Earlier PIO-based revisions had
// fractional dividers at every 256× combination and at 96 kHz × 128× (the
// PIO toggle program's pio_clk = 2 × MCK halved divider precision).

void audio_i2s_mck_setup(uint pin) {
    // "Claim a pin, don't drive it."  Actual GPOUTn block configuration is
    // deferred to the first set_enabled(true) call so we don't burn a clock
    // generator at boot when the user hasn't asked for MCK.  This matches
    // the pre-GPOUT lifecycle: callers expect setup() to be safe and silent.
    mck_pin_current = (uint8_t)pin;
    mck_running = false;
    mck_div_24_8 = 0u;
    printf("MCK setup: GPIO %u (CLK_GPOUTn-driven; not yet running)\n", pin);
}

void audio_i2s_mck_set_enabled(bool enabled) {
    // setup() has the contract of seeding mck_pin_current.  If a caller
    // enables before setup() they get a no-op (matches the old "mck_pio
    // == NULL" guard semantics).
    if (mck_pin_current == 0xFFu) return;

    if (enabled) {
        if (mck_running) return;  // already on — no-op (idempotent)
        if (mck_div_24_8 == 0u) {
            // update_frequency() was never called.  Refusing here is the
            // safe option: enabling with an undefined divider would let
            // CLK_GPOUTn use whatever DIV register value it last had,
            // which on a fresh boot can be 0 → undefined hardware behaviour.
            printf("MCK enable: no divider configured; refusing\n");
            return;
        }
        // clock_gpio_init_int_frac8() routes the pad mux to the CLK_GPOUTn
        // block selected by GPIO_TO_GPOUT_CLOCK_HANDLE(pin), loads the 24.8
        // divider, sets AUXSRC = clk_sys, and asserts ENABLE.  All four
        // GPOUTn blocks share the same AUXSRC encoding for clk_sys, so we
        // can use the GPOUT0 macro symbol regardless of which block the
        // pin actually maps to.  Calling this again with a new divider is
        // glitchless and drops no pin transitions.
        clock_gpio_init_int_frac8(mck_pin_current,
                                  CLOCKS_CLK_GPOUT0_CTRL_AUXSRC_VALUE_CLK_SYS,
                                  mck_div_24_8 >> 8u,
                                  (uint8_t)(mck_div_24_8 & 0xFFu));
        mck_running = true;
        printf("MCK enabled on GPIO %u\n", (uint)mck_pin_current);
    } else {
        if (!mck_running) return;  // already off — no-op
        // The Pico SDK exposes no public API to stop a CLK_GPOUTn generator,
        // only to disconnect the pad mux.  That's sufficient for the user-
        // visible "MCK off" semantics: the pin floats (we drive GPIO_IN to
        // make that explicit), no clock leaves the chip.  The generator
        // continues running internally — quiescent draw is a few µA, well
        // below the noise floor of the rest of the design.
        gpio_set_function(mck_pin_current, GPIO_FUNC_NULL);
        gpio_set_dir(mck_pin_current, GPIO_IN);
        mck_running = false;
        printf("MCK disabled on GPIO %u\n", (uint)mck_pin_current);
    }
}

void audio_i2s_mck_update_frequency(uint32_t sample_freq, uint32_t multiplier) {
    if (mck_pin_current == 0xFFu) return;

    // Defensive fallback for unexpected wire/flash values.  The vendor
    // command layer already restricts the wire encoding to {0, 1} ↔
    // {128, 256}, but a stale preset or a bulk_params payload from an
    // older firmware could still smuggle in a different number.
    if (multiplier != 128 && multiplier != 256) {
        printf("MCK invalid multiplier %u, forcing 128\n", (uint)multiplier);
        multiplier = 128;
    }

    uint32_t sys_clk = clock_get_hz(clk_sys);

    // 24.8 fixed-point divider:
    //   div         = sys_clk / MCK = sys_clk / (Fs × multiplier)
    //   div_24.8    = div × 256
    //               = sys_clk × 256 / (Fs × multiplier)
    //
    // NB: the previous PIO toggle program needed a ÷2 in the denominator
    // (PIO clk = 2 × MCK because the program emits one transition per
    // PIO cycle, so a full MCK period spans two PIO cycles).  With
    // CLK_GPOUTn the divider applies one-to-one — net result: 2× more
    // effective divider precision at the same Fs.  See the reference
    // table at the top of this section for which Fs/mult combinations
    // are now integer.
    //
    // 64-bit intermediate avoids overflow: sys_clk × 256 for sys_clk =
    // 307.2 MHz already exceeds 2^32.
    uint64_t num = (uint64_t)sys_clk * 256u;
    uint64_t den = (uint64_t)sample_freq * multiplier;
    uint32_t divider = (uint32_t)(num / den);

    printf("MCK divider 0x%x/256 (%u.%u) for %d Hz × %u = %u Hz (CLK_GPOUTn)\n",
           (uint)divider, (uint)(divider >> 8), (uint)(divider & 0xff),
           (int)sample_freq, (uint)multiplier,
           (uint)(sample_freq * multiplier));

    assert(divider < 0x1000000);
    mck_div_24_8 = divider;

    if (mck_running) {
        // Glitchless reload: re-call clock_gpio_init_int_frac8() with the
        // new divider.  AUXSRC stays clk_sys, ENABLE stays asserted, the
        // pad mux stays connected — only the DIV register changes.
        clock_gpio_init_int_frac8(mck_pin_current,
                                  CLOCKS_CLK_GPOUT0_CTRL_AUXSRC_VALUE_CLK_SYS,
                                  divider >> 8u,
                                  (uint8_t)(divider & 0xFFu));
    }
}

void audio_i2s_mck_change_pin(uint new_pin) {
    if (mck_pin_current == 0xFFu) return;
    // Vendor-layer contract: caller has already verified !mck_running.  The
    // contract exists because rerouting CLK_GPOUTn to a new pin while the
    // generator is live is fiddly (potentially routes both pins for a
    // cycle) and not worth the complexity for a config knob the user only
    // touches at setup.
    assert(!mck_running);

    // Pure book-keeping change — no hardware until next set_enabled(true),
    // which calls clock_gpio_init_int_frac8(new_pin, ...).  That call
    // inspects the pin number and configures the appropriate CLK_GPOUTn
    // block via GPIO_TO_GPOUT_CLOCK_HANDLE().
    mck_pin_current = (uint8_t)new_pin;
    printf("MCK pin changed to GPIO %u (takes effect on next enable)\n", new_pin);
}

uint8_t audio_i2s_mck_get_pin(void) {
    return mck_pin_current;
}

bool audio_i2s_mck_is_enabled(void) {
    return mck_running;
}

I2S_TIME_CRITICAL
void audio_i2s_mck_set_divider(uint32_t div_24_8) {
    // Servo path — bypasses the Fs × multiplier math.  Same hot-reload
    // mechanics as update_frequency(): if running, write the new divider
    // glitchlessly; otherwise stash it for the next enable.
    if (mck_pin_current == 0xFFu) return;
    assert(div_24_8 < 0x1000000);
    mck_div_24_8 = div_24_8;
    if (mck_running) {
        clock_gpio_init_int_frac8(mck_pin_current,
                                  CLOCKS_CLK_GPOUT0_CTRL_AUXSRC_VALUE_CLK_SYS,
                                  div_24_8 >> 8u,
                                  (uint8_t)(div_24_8 & 0xFFu));
    }
}

void audio_i2s_mck_apply_state(uint pin, bool enabled,
                               uint32_t sample_freq, uint32_t multiplier) {
    // Apply-path sync helper — see header for rationale.  Sequences the
    // three primitives so the library tracks a desired (pin, enabled,
    // Fs, mult) tuple atomically.  No-op until setup() has run.
    if (mck_pin_current == 0xFFu) return;

    // 1. Pin sync.  change_pin contractually requires !mck_running, so
    //    drop the GPOUTn pad mux first if the pin is changing while the
    //    clock is live.  This is the only place where the pin can change
    //    while MCK is running — the vendor command path enforces "disable
    //    first" at the validation layer; the apply path didn't, hence
    //    this helper.
    if ((uint8_t)pin != mck_pin_current) {
        if (mck_running) {
            audio_i2s_mck_set_enabled(false);
        }
        audio_i2s_mck_change_pin(pin);
    }

    if (enabled) {
        // 2. Recompute divider for current Fs/multiplier.  If MCK is
        //    already running, this is a glitchless DIV reload; if off,
        //    just stashes mck_div_24_8 for the upcoming set_enabled.
        audio_i2s_mck_update_frequency(sample_freq, multiplier);
        // 3. Start it if not already.
        if (!mck_running) {
            audio_i2s_mck_set_enabled(true);
        }
    } else {
        // Caller wants MCK off — stop it if running.
        if (mck_running) {
            audio_i2s_mck_set_enabled(false);
        }
    }
}
