/*
 * Copyright (c) 2026 WeebLabs
 *
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Multi-instance I2S audio output library for RP2040/RP2350.
 *
 * Architecture mirrors pico_audio_spdif_multi: instance-based API, shared
 * DMA IRQ handler with reference-counted enable/disable, per-PIO-block
 * program caching, and synchronized multi-instance start.
 *
 * Key differences from SPDIF:
 *   - PIO program: 8-instruction I2S master (vs 4-instruction SPDIF NRZI)
 *   - Consumer stride: 8 bytes/sample (2 × int32) vs 16 bytes (2 × subframe)
 *   - DMA words per sample: 2 (vs 4 for SPDIF)
 *   - Encoding: simple left-shift by 8 (vs NRZI lookup table)
 *   - No preambles, channel status, or block structure
 *   - BCK/LRCLK shared across instances (side-set), data pin independent
 *   - Includes MCK generator on a separate PIO SM
 */

// RP2350: Force time-critical functions into RAM to avoid XIP cache misses
#if PICO_RP2350
#define I2S_TIME_CRITICAL __attribute__((noinline, section(".time_critical")))
#else
#define I2S_TIME_CRITICAL
#endif

#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <stdlib.h>
#include "pico/audio_i2s_multi.h"
#include "audio_i2s_clkout.pio.h"
#include "audio_i2s_clkout_only.pio.h"
#include "audio_i2s_dataout.pio.h"
#include "audio_i2s_datain.pio.h"
// MCK is generated by the hardware CLK_GPOUT block (no PIO program needed).
// See clock_gpio_init() in hardware/clocks.h.
#include "hardware/pio.h"
#include "hardware/gpio.h"
#include "hardware/dma.h"
#include "hardware/irq.h"
#include "hardware/clocks.h"
#include "hardware/sync.h"

#ifndef container_of
#define container_of(ptr, type, member) \
    ((type *)((char *)(ptr) - offsetof(type, member)))
#endif

// ---------------------------------------------------------------------------
// Global shared state
// ---------------------------------------------------------------------------

// PIO program offsets per PIO block — loaded once per block, persist forever
static int i2s_pio_program_offset[3] = {-1, -1, -1};          // Master program
static int i2s_slave_pio_program_offset[3] = {-1, -1, -1};    // Slave program

// Which registered I2S instance index is the clock master (-1 = none).
// Only the master SM runs the master PIO program (side-set drives BCK/LRCLK).
// All other I2S SMs run the slave program (data-only, no clock output).
static int8_t i2s_clock_master_index = -1;

// Instance registry for DMA IRQ handler
static audio_i2s_instance_t *i2s_instances[PICO_AUDIO_I2S_MAX_INSTANCES];
static uint i2s_instance_count = 0;

// Track whether shared IRQ handler is installed per DMA IRQ line
static bool i2s_irq_handler_installed[2] = {false, false};

// Reference count for DMA IRQ enable/disable
static uint8_t i2s_irq_enable_count[2] = {0, 0};

// ---------------------------------------------------------------------------
// MCK generator state — driven by the hardware CLK_GPOUT block, not a PIO SM.
// CLK_GPOUTn divides clk_sys (PLL_SYS post-divider) by a 24.8 fixed-point
// divider and routes the result directly to a GPIO pad with no PIO/CPU
// involvement.  Lower jitter than the PIO toggle program and gives integer
// dividers for 48 kHz × 256× (12.288 MHz, divider 25.0) and 96 kHz × 128×
// (12.288 MHz, divider 25.0) which the PIO route could only produce as
// fractional 12.5.  See GPIO_TO_GPOUT_CLOCK_HANDLE in pico-sdk/hardware/clocks.h.
// ---------------------------------------------------------------------------

static uint8_t mck_pin_current = 0xFFu;
static bool    mck_running = false;
static uint32_t mck_div_24_8 = 0u;  // last-computed CLK_GPOUTn.DIV value

// ---------------------------------------------------------------------------
// Clocks-only master ("phantom") state. Managed by election_apply: installed
// when ≥1 RX is registered and 0 TX is registered; uninstalled when a TX
// becomes registered or when the last RX detaches. Direct callers should
// NOT use audio_i2s_clock_domain_clkout_only_*; they're library-internal.
// ---------------------------------------------------------------------------

static int  i2s_clkout_only_program_offset[3] = {-1, -1, -1};
static PIO  i2s_clkout_only_pio = NULL;
static int  i2s_clkout_only_sm = -1;
static uint8_t i2s_clkout_only_bck_pin = 0xFFu;
static uint32_t i2s_clkout_only_freq = 0u;
static bool i2s_clkout_only_active_flag = false;

// ---------------------------------------------------------------------------
// RX program offset cache (per-PIO-block, loaded once)
// ---------------------------------------------------------------------------

static int i2s_datain_program_offset[3] = {-1, -1, -1};

// ---------------------------------------------------------------------------
// RX instance registry — election treats RX presence as "phantom needed if
// no TX is registered." Kept to a fixed-size array (no dynamic alloc) for
// ISR-safe iteration.
// ---------------------------------------------------------------------------

#ifndef PICO_AUDIO_I2S_MAX_RX_INSTANCES
#define PICO_AUDIO_I2S_MAX_RX_INSTANCES 4
#endif

static audio_i2s_rx_instance_t *i2s_rx_instances[PICO_AUDIO_I2S_MAX_RX_INSTANCES];
static uint i2s_rx_instance_count = 0;

// ---------------------------------------------------------------------------
// Clock domain configuration (set by audio_i2s_clock_domain_configure)
// ---------------------------------------------------------------------------

static uint8_t i2s_cd_bck_pin = 0xFFu;
static uint8_t i2s_cd_phantom_pio_idx = 0xFFu;
static uint8_t i2s_cd_phantom_sm = 0xFFu;

// ---------------------------------------------------------------------------
// Bulk-change transaction state
// ---------------------------------------------------------------------------

static int  i2s_transaction_depth = 0;
static bool i2s_deferred_election = false;

// ---------------------------------------------------------------------------
// Forward declarations
// ---------------------------------------------------------------------------

static void __isr __time_critical_func(audio_i2s_dma_irq_handler)(void);
static void __time_critical_func(i2s_audio_start_dma_transfer)(audio_i2s_instance_t *inst);
static void reinit_tx_as_master(audio_i2s_instance_t *inst);
static void reinit_tx_as_slave(audio_i2s_instance_t *inst);
static void election_apply(void);
static void election_request(void);

// ---------------------------------------------------------------------------
// PIO block index helper
// ---------------------------------------------------------------------------

static PIO i2s_pio_block_from_index(uint8_t idx) {
    switch (idx) {
        case 0: return pio0;
        case 1: return pio1;
#if NUM_PIOS > 2
        case 2: return pio2;
#endif
        default: panic("Invalid PIO index %d", idx);
    }
}

// ---------------------------------------------------------------------------
// Clock divider calculation
// ---------------------------------------------------------------------------

// I2S timing:
//   Each audio bit takes 2 PIO clocks (out + jmp instruction pair).
//   32 bits/channel × 2 channels = 64 bits/frame × 2 clocks/bit = 128 PIO
//   clocks per stereo sample.
//
//   PIO_clk = sample_freq × 128
//
//   divider (24.8 fixed-point) = sys_clk × 256 / PIO_clk
//                               = sys_clk × 256 / (sample_freq × 128)
//                               = sys_clk × 2 / sample_freq
//
//   At 307.2 MHz / 48 kHz: divider = 12800 → integer 50, fractional 0
//   (zero PIO clock jitter)

// Compute the I2S clock divider in 24.8 fixed-point for a given sample rate.
static uint32_t i2s_compute_divider(uint32_t sample_freq) {
    uint32_t system_clock_frequency = clock_get_hz(clk_sys);
    assert(system_clock_frequency < 0x40000000);

    // divider = sys_clk * 2 / sample_freq (ceiling division to match SPDIF rounding)
    uint64_t num = (uint64_t)system_clock_frequency * 2;
    uint32_t divider = (uint32_t)((num + sample_freq - 1) / sample_freq);
    assert(divider < 0x1000000);
    return divider;
}

// Update clock divider for a single instance AND all other I2S instances on
// the same PIO block.  All I2S SMs must run at the same rate because they
// share BCK/LRCLK timing from the master.
static void i2s_update_pio_frequency(audio_i2s_instance_t *inst, uint32_t sample_freq) {
    uint32_t divider = i2s_compute_divider(sample_freq);

    printf("I2S clock divider 0x%x/256 (%u.%u) for %d Hz (all %d instances)\n",
           (uint)divider, (uint)(divider >> 8), (uint)(divider & 0xff),
           (int)sample_freq, i2s_instance_count);

    // Apply to ALL registered I2S instances on the same PIO block
    for (uint i = 0; i < i2s_instance_count; i++) {
        audio_i2s_instance_t *other = i2s_instances[i];
        if (other && other->pio == inst->pio) {
            pio_sm_set_clkdiv_int_frac(other->pio, other->pio_sm,
                                        divider >> 8u, divider & 0xffu);
            other->freq = sample_freq;
        }
    }
    // Also update the triggering instance (it may not be registered yet during setup)
    pio_sm_set_clkdiv_int_frac(inst->pio, inst->pio_sm,
                                divider >> 8u, divider & 0xffu);
    inst->freq = sample_freq;
}

// ---------------------------------------------------------------------------
// Connection callbacks
// ---------------------------------------------------------------------------

I2S_TIME_CRITICAL
static audio_buffer_t *i2s_wrap_consumer_take(audio_connection_t *connection, bool block) {
    // Recover the instance from the embedded connection
    audio_i2s_instance_t *inst = container_of(
        (struct producer_pool_blocking_give_connection *)connection,
        audio_i2s_instance_t, connection);

    // Support dynamic frequency shifting
    if (connection->producer_pool->format->sample_freq != inst->freq) {
        i2s_update_pio_frequency(inst, connection->producer_pool->format->sample_freq);
    }
    return consumer_pool_take_buffer_default(connection, block);
}

// ---------------------------------------------------------------------------
// I2S sample encoding: left-justify 24-bit audio into 32-bit I2S frames
//
// Producer buffer: interleaved int32_t L/R pairs, 24-bit audio in bits [23:0]
// Consumer buffer: interleaved int32_t L/R pairs, 24-bit audio in bits [31:8]
//
// The PIO shifts MSB-first, so audio must be in the upper 24 bits.
// The lower 8 bits are zero (standard I2S padding).
//
// This is dramatically simpler than SPDIF BMC encoding — just a left-shift.
// ---------------------------------------------------------------------------

// I2S producer-give callback.
//
// Follows the same pattern as SPDIF's stereo_to_spdif_producer_give_s32():
//   1. Take a free consumer buffer (blocking — waits for DMA to return one)
//   2. Convert producer samples into consumer format
//   3. Return producer buffer to free list via queue_free_audio_buffer()
//      (NOT give_audio_buffer, which would re-trigger this callback → recursion)
//   4. Give consumer buffer to prepared list for DMA pickup
//
I2S_TIME_CRITICAL
static void i2s_wrap_producer_give(audio_connection_t *connection, audio_buffer_t *buffer) {
    // Mirrors producer_pool_blocking_give(): consume producer samples into
    // free consumer buffers, then queue completed consumer buffers to prepared.
    struct producer_pool_blocking_give_connection *pbc =
        (struct producer_pool_blocking_give_connection *)connection;
    uint32_t pos = 0;

    while (pos < buffer->sample_count) {
        if (!pbc->current_consumer_buffer) {
            pbc->current_consumer_buffer = get_free_audio_buffer(connection->consumer_pool, true);
            pbc->current_consumer_buffer_pos = 0;
        }

        uint32_t in_remaining = buffer->sample_count - pos;
        uint32_t out_remaining = pbc->current_consumer_buffer->max_sample_count -
                                 pbc->current_consumer_buffer_pos;
        uint32_t sample_count = in_remaining < out_remaining ? in_remaining : out_remaining;

        int32_t *src = ((int32_t *)buffer->buffer->bytes) + (pos * 2);
        int32_t *dst = ((int32_t *)pbc->current_consumer_buffer->buffer->bytes) +
                       (pbc->current_consumer_buffer_pos * 2);

        // PIO enters at the left channel slot — DMA order matches producer order (L,R).
        // Left-shift by 8 to place 24-bit audio at MSB for I2S MSB-first output.
        for (uint32_t i = 0; i < sample_count; i++) {
            dst[i * 2]     = src[i * 2] << 8;     // L sample
            dst[i * 2 + 1] = src[i * 2 + 1] << 8; // R sample
        }

        pos += sample_count;
        pbc->current_consumer_buffer_pos += sample_count;

        if (pbc->current_consumer_buffer_pos ==
            pbc->current_consumer_buffer->max_sample_count) {
            pbc->current_consumer_buffer->sample_count =
                pbc->current_consumer_buffer->max_sample_count;
            queue_full_audio_buffer(connection->consumer_pool,
                                    pbc->current_consumer_buffer);
            pbc->current_consumer_buffer = NULL;
        }
    }

    // Return producer buffer directly to free list (avoids recursive callback).
    queue_free_audio_buffer(connection->producer_pool, buffer);
}

// ---------------------------------------------------------------------------
// audio_i2s_setup
// ---------------------------------------------------------------------------

const audio_format_t *audio_i2s_setup(audio_i2s_instance_t *inst,
                                       const audio_format_t *intended_audio_format,
                                       const audio_i2s_config_t *config) {
    assert(i2s_instance_count < PICO_AUDIO_I2S_MAX_INSTANCES);

    // Store hardware config into instance.
    // The clock_master flag in config is IGNORED — election decides roles
    // internally. Every instance is initialized as a slave (data-only)
    // placeholder; the election that runs after registration may reinit
    // the lowest-index instance as master via reinit_tx_as_master().
    inst->pio = i2s_pio_block_from_index(config->pio);
    inst->pio_sm = config->pio_sm;
    inst->dma_channel = config->dma_channel;
    inst->dma_irq = config->dma_irq;
    inst->data_pin = config->data_pin;
    inst->clock_pin_base = config->clock_pin_base;
    inst->clock_master = false;  // election may flip this; ignore config->clock_master
    inst->playing_buffer = NULL;
    inst->freq = 0;
    inst->enabled = false;
    inst->words_consumed = 0;
    inst->current_transfer_words = 0;
    inst->consumer_pool = NULL;

    // This instance struct may be reused across output-type switches.
    // Clear carry-over connection state so a stale staging pointer from a
    // previous lifetime cannot be consumed after reconnect.
    memset(&inst->connection, 0, sizeof(inst->connection));

    // Assert all instances share the same DMA IRQ line
    if (i2s_instance_count > 0) {
        assert(inst->dma_irq == i2s_instances[0]->dma_irq);
    }

    // GPIO init for data pin (always)
    pio_gpio_init(inst->pio, config->data_pin);

    // Claim SM
    pio_sm_claim(inst->pio, inst->pio_sm);

    // Always initialize as data-only slave. The election (run after
    // registration below) reinitializes this SM as master via the
    // audio_i2s_clkout program if it landed at registry index 0.
    if (i2s_slave_pio_program_offset[config->pio] < 0) {
        i2s_slave_pio_program_offset[config->pio] =
            pio_add_program(inst->pio, &audio_i2s_dataout_program);
    }
    {
        uint offset = (uint)i2s_slave_pio_program_offset[config->pio];
        audio_i2s_dataout_program_init(inst->pio, inst->pio_sm, offset,
                                         config->data_pin);
    }
    printf("I2S setup: SM%d (data GPIO %d, election pending)\n",
           inst->pio_sm, inst->data_pin);

    // Initialize per-instance silence buffer (DMA-sized, all zeros)
    inst->consumer_buffer_format.format = &inst->consumer_format;
    inst->silence_buffer.sample_count = PICO_AUDIO_I2S_DMA_SAMPLE_COUNT;
    inst->silence_buffer.max_sample_count = PICO_AUDIO_I2S_DMA_SAMPLE_COUNT;
    inst->silence_buffer.format = &inst->consumer_buffer_format;

    // I2S silence: 48 samples × 2 channels × 4 bytes = 384 bytes
    const size_t silence_bytes = PICO_AUDIO_I2S_DMA_SAMPLE_COUNT * 2 * sizeof(int32_t);
    inst->silence_buffer.buffer = pico_buffer_alloc(silence_bytes);
    if (!inst->silence_buffer.buffer) {
        panic("I2S setup: failed to allocate silence buffer");
    }
    memset(inst->silence_buffer.buffer->bytes, 0, silence_bytes);

    __mem_fence_release();

    // DMA setup
    dma_channel_claim(inst->dma_channel);

    dma_channel_config dma_config = dma_channel_get_default_config(inst->dma_channel);
    channel_config_set_dreq(&dma_config, pio_get_dreq(inst->pio, inst->pio_sm, true));

#if PICO_RP2350
    // RP2350 requires explicit high priority for DMA to prevent audio underruns
    channel_config_set_high_priority(&dma_config, true);
#endif

    dma_channel_configure(inst->dma_channel,
                          &dma_config,
                          &inst->pio->txf[inst->pio_sm],  // dest: PIO TX FIFO
                          NULL,   // src: set per transfer
                          0,      // count: set per transfer
                          false   // don't trigger yet
    );

    // Install shared IRQ handler once per DMA IRQ line
    if (!i2s_irq_handler_installed[inst->dma_irq]) {
        irq_add_shared_handler(DMA_IRQ_0 + inst->dma_irq, audio_i2s_dma_irq_handler,
                               PICO_SHARED_IRQ_HANDLER_DEFAULT_ORDER_PRIORITY);
        i2s_irq_handler_installed[inst->dma_irq] = true;
    }

    // Clear any stale completion flag from prior channel users before unmasking.
    dma_irqn_acknowledge_channel(inst->dma_irq, inst->dma_channel);
    dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, 1);

    // Register instance atomically against DMA IRQ iteration.
    uint32_t save = save_and_disable_interrupts();
    i2s_instances[i2s_instance_count++] = inst;
    restore_interrupts(save);

    // Trigger election. Outside a transaction, this runs immediately and
    // reinit's this SM as master if it's the first registered TX. Inside
    // a transaction, defer until commit.
    election_request();

    return intended_audio_format;
}

// ---------------------------------------------------------------------------
// audio_i2s_connect_extra
// ---------------------------------------------------------------------------

bool audio_i2s_connect_extra(audio_i2s_instance_t *inst,
                              audio_buffer_pool_t *producer,
                              bool buffer_on_give, uint buffer_count,
                              audio_connection_t *connection) {
    printf("Connecting PIO I2S audio (SM%d, data GPIO %d, BCK GPIO %d)\n",
           inst->pio_sm, inst->data_pin, inst->clock_pin_base);

    assert(producer->format->format == AUDIO_BUFFER_FORMAT_PCM_S32);

    // Consumer format: raw PCM for I2S (2 × int32 per stereo sample)
    inst->consumer_format.format = AUDIO_BUFFER_FORMAT_PIO_I2S;
    inst->consumer_format.sample_freq = producer->format->sample_freq;
    inst->consumer_format.channel_count = 2;
    inst->consumer_buffer_format.format = &inst->consumer_format;
    inst->consumer_buffer_format.sample_stride = 2 * sizeof(int32_t);  // 8 bytes

    // Create consumer pool: buffer_count buffers × DMA_SAMPLE_COUNT samples
    inst->consumer_pool = audio_new_consumer_pool(&inst->consumer_buffer_format,
                                                   buffer_count,
                                                   PICO_AUDIO_I2S_DMA_SAMPLE_COUNT);
    if (!inst->consumer_pool) {
        panic("I2S connect failed: consumer pool allocation failed");
    }

    // Zero-fill all consumer buffers (I2S silence is just zeros)
    for (audio_buffer_t *buffer = inst->consumer_pool->free_list; buffer; buffer = buffer->next) {
        memset(buffer->buffer->bytes, 0,
               PICO_AUDIO_I2S_DMA_SAMPLE_COUNT * 2 * sizeof(int32_t));
    }

    i2s_update_pio_frequency(inst, producer->format->sample_freq);

    __mem_fence_release();

    if (!connection) {
        printf("I2S stereo 24-bit at %d Hz\n", (int)producer->format->sample_freq);

        // Initialize the embedded connection callbacks
        inst->connection.core.consumer_pool_take = i2s_wrap_consumer_take;
        inst->connection.core.consumer_pool_give = consumer_pool_give_buffer_default;
        inst->connection.core.producer_pool_take = producer_pool_take_buffer_default;
        inst->connection.core.producer_pool_give = i2s_wrap_producer_give;
        connection = &inst->connection.core;
    }
    audio_complete_connection(connection, producer, inst->consumer_pool);
    return true;
}

// ---------------------------------------------------------------------------
// DMA transfer
// ---------------------------------------------------------------------------

static void __time_critical_func(i2s_audio_start_dma_transfer)(audio_i2s_instance_t *inst) {
    assert(!inst->playing_buffer);
    audio_buffer_t *ab = take_audio_buffer(inst->consumer_pool, false);

    inst->playing_buffer = ab;
    if (!ab) {
        // Play silence on underrun
        ab = &inst->silence_buffer;

        extern int overruns;
        extern volatile bool preset_loading;
        if (!preset_loading)
            overruns++;
    }

    // I2S: 2 DMA words per stereo sample (1 int32 L + 1 int32 R)
    uint32_t transfer_words = ab->sample_count * 2;
    inst->current_transfer_words = transfer_words;
    dma_channel_transfer_from_buffer_now(inst->dma_channel, ab->buffer->bytes, transfer_words);
}

// ---------------------------------------------------------------------------
// DMA IRQ handler — iterates all registered I2S instances
// ---------------------------------------------------------------------------

void __isr __time_critical_func(audio_i2s_dma_irq_handler)(void) {
    for (uint i = 0; i < i2s_instance_count; i++) {
        audio_i2s_instance_t *inst = i2s_instances[i];
        if (dma_irqn_get_channel_status(inst->dma_irq, inst->dma_channel)) {
            dma_irqn_acknowledge_channel(inst->dma_irq, inst->dma_channel);

            // Track total DMA words consumed (for USB feedback endpoint)
            inst->words_consumed += inst->current_transfer_words;

            // Free the buffer we just finished playing
            if (inst->playing_buffer) {
                extern volatile uint32_t pio_samples_dma;
                pio_samples_dma++;

                give_audio_buffer(inst->consumer_pool, inst->playing_buffer);
                inst->playing_buffer = NULL;
            }
            i2s_audio_start_dma_transfer(inst);
        }
    }
}

// ---------------------------------------------------------------------------
// audio_i2s_set_enabled
// ---------------------------------------------------------------------------

void audio_i2s_set_enabled(audio_i2s_instance_t *inst, bool enabled) {
    if (enabled != inst->enabled) {
#ifndef NDEBUG
        if (enabled) {
            puts("Enabling PIO I2S audio\n");
            printf("(on core %d)\n", get_core_num());
        }
#endif
        if (enabled) {
            if (i2s_irq_enable_count[inst->dma_irq]++ == 0)
                irq_set_enabled(DMA_IRQ_0 + inst->dma_irq, true);
            i2s_audio_start_dma_transfer(inst);
            pio_sm_set_enabled(inst->pio, inst->pio_sm, true);
        } else {
            pio_sm_set_enabled(inst->pio, inst->pio_sm, false);
            if (--i2s_irq_enable_count[inst->dma_irq] == 0)
                irq_set_enabled(DMA_IRQ_0 + inst->dma_irq, false);
        }
        inst->enabled = enabled;
    }
}

// ---------------------------------------------------------------------------
// audio_i2s_change_data_pin
// ---------------------------------------------------------------------------

void audio_i2s_change_data_pin(audio_i2s_instance_t *inst, uint new_pin) {
    assert(!inst->enabled);

    // Mask DMA IRQ for this channel during reinit
    dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, false);

    // Abort any stale DMA transfer
    dma_channel_abort(inst->dma_channel);

    // Return in-flight buffer to consumer pool
    if (inst->playing_buffer != NULL) {
        give_audio_buffer(inst->consumer_pool, inst->playing_buffer);
        inst->playing_buffer = NULL;
    }

    // Release old data pin from PIO mux -> high-Z
    gpio_set_function(inst->data_pin, GPIO_FUNC_NULL);
    gpio_set_dir(inst->data_pin, GPIO_IN);

    // Claim new data pin for PIO
    pio_gpio_init(inst->pio, new_pin);

    // Reinitialize SM with new data pin using the correct program for role
    uint pio_idx = pio_get_index(inst->pio);
    if (inst->clock_master) {
        assert(i2s_pio_program_offset[pio_idx] >= 0);
        uint offset = (uint)i2s_pio_program_offset[pio_idx];
        audio_i2s_clkout_program_init(inst->pio, inst->pio_sm, offset,
                                   new_pin, inst->clock_pin_base);
    } else {
        assert(i2s_slave_pio_program_offset[pio_idx] >= 0);
        uint offset = (uint)i2s_slave_pio_program_offset[pio_idx];
        audio_i2s_dataout_program_init(inst->pio, inst->pio_sm, offset, new_pin);
    }

    // Restore clock divider (pio_sm_init resets it to default)
    if (inst->freq != 0) {
        i2s_update_pio_frequency(inst, inst->freq);
    }

    // pio_sm_init() reset this SM's clock divider phase accumulator.
    // Restart ALL I2S SM dividers on this PIO block so they stay phase-aligned.
    // Without this, the re-inited SM's divider is at phase 0 while others are
    // at arbitrary phases — causing permanent bit-level misalignment.
    {
        uint32_t sm_mask = 0;
        for (uint i = 0; i < i2s_instance_count; i++) {
            if (i2s_instances[i]->pio == inst->pio)
                sm_mask |= (1u << i2s_instances[i]->pio_sm);
        }
        if (sm_mask)
            pio_clkdiv_restart_sm_mask(inst->pio, sm_mask);
    }

    // Clear any stale DMA completion flag, then unmask
    dma_irqn_acknowledge_channel(inst->dma_irq, inst->dma_channel);
    dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, true);

    inst->data_pin = new_pin;
}

// ---------------------------------------------------------------------------
// audio_i2s_enable_sync — synchronized start for multiple instances
// ---------------------------------------------------------------------------

void audio_i2s_enable_sync(audio_i2s_instance_t *instances[], uint count) {
    assert(count > 0 && count <= PICO_AUDIO_I2S_MAX_INSTANCES);

    // Rewind each SM to a known program entry state before synchronous start.
    // pio_enable_sm_mask_in_sync() aligns divider phase, but does not reset
    // instruction position or shift counters. Without this reset, previously
    // running SMs can resume at different bit positions and produce data/clock
    // misalignment (audible as white-noise-like corruption).
    for (uint i = 0; i < count; i++) {
        audio_i2s_instance_t *inst = instances[i];
        uint pio_idx = pio_get_index(inst->pio);
        uint entry_pc;

        if (inst->clock_master) {
            assert(i2s_pio_program_offset[pio_idx] >= 0);
            entry_pc = (uint)i2s_pio_program_offset[pio_idx] + audio_i2s_clkout_offset_entry_point;
        } else {
            assert(i2s_slave_pio_program_offset[pio_idx] >= 0);
            entry_pc = (uint)i2s_slave_pio_program_offset[pio_idx] + audio_i2s_dataout_offset_entry_point;
        }

        pio_sm_clear_fifos(inst->pio, inst->pio_sm);
        pio_sm_restart(inst->pio, inst->pio_sm);
        pio_sm_exec(inst->pio, inst->pio_sm, pio_encode_jmp(entry_pc));
    }

    // Enable DMA IRQ and prime DMA for all instances
    for (uint i = 0; i < count; i++) {
        audio_i2s_instance_t *inst = instances[i];
        if (i2s_irq_enable_count[inst->dma_irq]++ == 0)
            irq_set_enabled(DMA_IRQ_0 + inst->dma_irq, true);
        i2s_audio_start_dma_transfer(inst);
    }

    // Build per-PIO-block SM bitmasks
    uint32_t pio_sm_mask[3] = {0, 0, 0};
    for (uint i = 0; i < count; i++) {
        audio_i2s_instance_t *inst = instances[i];
        for (uint p = 0; p < 3; p++) {
            PIO block = i2s_pio_block_from_index(p);
            if (inst->pio == block) {
                pio_sm_mask[p] |= (1u << inst->pio_sm);
                break;
            }
        }
    }

    // Disable interrupts briefly and start all PIO blocks synchronously
    uint32_t save = save_and_disable_interrupts();
    for (uint p = 0; p < 3; p++) {
        if (pio_sm_mask[p]) {
            pio_enable_sm_mask_in_sync(i2s_pio_block_from_index(p), pio_sm_mask[p]);
        }
    }
    restore_interrupts(save);

    // Mark all instances enabled
    for (uint i = 0; i < count; i++) {
        instances[i]->enabled = true;
    }
}

// ---------------------------------------------------------------------------
// audio_i2s_teardown — full cleanup for output type switching
// ---------------------------------------------------------------------------

void audio_i2s_teardown(audio_i2s_instance_t *inst) {
    // Disable if still running
    if (inst->enabled) {
        audio_i2s_set_enabled(inst, false);
    }

    // Mask DMA IRQ and abort
    dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, false);
    dma_channel_abort(inst->dma_channel);
    dma_irqn_acknowledge_channel(inst->dma_irq, inst->dma_channel);

    // Return in-flight buffer owned by this instance.
    if (inst->playing_buffer != NULL) {
        if (inst->consumer_pool != NULL) {
            give_audio_buffer(inst->consumer_pool, inst->playing_buffer);
        }
        inst->playing_buffer = NULL;
    }

    // Return any partially filled producer->consumer staging buffer.
    // This pointer lives in the embedded connection object, not the DMA path,
    // so teardown must explicitly drain it before freeing the pool.
    if (inst->connection.current_consumer_buffer != NULL) {
        if (inst->consumer_pool != NULL) {
            queue_free_audio_buffer(inst->consumer_pool,
                                    inst->connection.current_consumer_buffer);
        }
        inst->connection.current_consumer_buffer = NULL;
    }
    inst->connection.current_consumer_buffer_pos = 0;

    // Break bidirectional connection links before pool free so accidental
    // post-teardown take/give paths fail fast instead of touching freed memory.
    if (inst->consumer_pool &&
        inst->consumer_pool->connection == &inst->connection.core) {
        inst->consumer_pool->connection = NULL;
    }
    if (inst->connection.core.producer_pool &&
        inst->connection.core.producer_pool->connection == &inst->connection.core) {
        inst->connection.core.producer_pool->connection = NULL;
    }
    inst->connection.core.producer_pool_take = NULL;
    inst->connection.core.producer_pool_give = NULL;
    inst->connection.core.consumer_pool_take = NULL;
    inst->connection.core.consumer_pool_give = NULL;
    inst->connection.core.producer_pool = NULL;
    inst->connection.core.consumer_pool = NULL;

    // Free dynamic consumer pool allocations. Without this, repeated
    // output-type switching leaks heap and eventually crashes setup paths.
    if (inst->consumer_pool) {
        audio_free_buffer_pool(inst->consumer_pool);
        inst->consumer_pool = NULL;
    }

    // Free per-instance silence buffer allocated by setup().
    if (inst->silence_buffer.buffer) {
        free(inst->silence_buffer.buffer->bytes);
        inst->silence_buffer.buffer->bytes = NULL;
        inst->silence_buffer.buffer->size = 0;
        free(inst->silence_buffer.buffer);
        inst->silence_buffer.buffer = NULL;
    }
    inst->silence_buffer.sample_count = 0;
    inst->silence_buffer.max_sample_count = 0;
    inst->silence_buffer.format = NULL;

    // Release data pin
    gpio_set_function(inst->data_pin, GPIO_FUNC_NULL);
    gpio_set_dir(inst->data_pin, GPIO_IN);

    // Unclaim DMA channel and PIO SM
    dma_channel_unclaim(inst->dma_channel);
    pio_sm_unclaim(inst->pio, inst->pio_sm);

    // Remove from instance registry atomically against DMA IRQ iteration.
    bool was_master = inst->clock_master;
    uint32_t save = save_and_disable_interrupts();
    for (uint i = 0; i < i2s_instance_count; i++) {
        if (i2s_instances[i] == inst) {
            for (uint j = i; j < i2s_instance_count - 1; j++) {
                i2s_instances[j] = i2s_instances[j + 1];
            }
            i2s_instance_count--;
            break;
        }
    }

    // Master election bookkeeping
    if (was_master) {
        i2s_clock_master_index = -1;

        if (i2s_instance_count == 0) {
            // Last I2S instance removed — release BCK/LRCLK to high-Z
            gpio_set_function(inst->clock_pin_base, GPIO_FUNC_NULL);
            gpio_set_dir(inst->clock_pin_base, GPIO_IN);
            gpio_set_function(inst->clock_pin_base + 1, GPIO_FUNC_NULL);
            gpio_set_dir(inst->clock_pin_base + 1, GPIO_IN);
        }
        // If other instances remain, do NOT release BCK/LRCLK — the pins
        // hold their last driven level (no high-Z glitch). The caller is
        // responsible for promoting a slave to master and restarting in sync.
    }
    restore_interrupts(save);

    printf("I2S teardown: SM%d %s, data GPIO %d (instances remaining: %d)\n",
           inst->pio_sm, was_master ? "(was master)" : "(slave)",
           inst->data_pin, i2s_instance_count);

    // Trigger re-election. If a TX remains, it gets promoted to master.
    // If only RX remains, the phantom is installed. If nothing remains,
    // the phantom (if any) is uninstalled and the clock domain goes idle.
    election_request();
}

// ---------------------------------------------------------------------------
// Atomic frequency update for all I2S instances (called on sample rate change)
// ---------------------------------------------------------------------------

void audio_i2s_update_all_frequencies(uint32_t sample_freq) {
    // Early-out if there's nothing on the I2S clock domain at all.
    if (i2s_instance_count == 0 &&
        i2s_rx_instance_count == 0 &&
        !i2s_clkout_only_active_flag) return;

    uint32_t divider = i2s_compute_divider(sample_freq);

    // Update phantom (clkout-only) SM divider if it's running.
    // Done before TX restart so all clock-domain SMs reach the new rate
    // together; the phantom is on its own SM and self-runs (no DMA).
    if (i2s_clkout_only_active_flag) {
        audio_i2s_clock_domain_clkout_only_set_frequency(sample_freq);
    }

    // Update RX SMs at the new rate. Each RX SM is on its own PIO and
    // self-syncs on LRCLK low edge, so we just disable, update divider,
    // re-enable. The first frame after re-enable is correctly aligned.
    for (uint i = 0; i < i2s_rx_instance_count; i++) {
        audio_i2s_rx_instance_t *rx = i2s_rx_instances[i];
        bool was_active = rx->active;
        if (was_active) audio_i2s_rx_set_enabled(rx, false);
        audio_i2s_rx_set_frequency(rx, sample_freq);
        if (was_active) audio_i2s_rx_set_enabled(rx, true);
    }

    if (i2s_instance_count == 0) return;

    // Update divider on ALL instances and build masks for restart.
    // all_sm_mask covers every registered SM for clkdiv phase reset.
    uint32_t all_sm_mask = 0;
    audio_i2s_instance_t *active[PICO_AUDIO_I2S_MAX_INSTANCES];
    uint active_count = 0;
    PIO pio = NULL;

    for (uint i = 0; i < i2s_instance_count; i++) {
        audio_i2s_instance_t *inst = i2s_instances[i];

        // Quiesce currently enabled instances before sync re-enable.
        // This keeps i2s_irq_enable_count balanced: audio_i2s_enable_sync()
        // increments the refcount, so we must pair it with a decrement here.
        // Also abort DMA to avoid overlapping old/new transfers across restart.
        if (inst->enabled) {
            audio_i2s_set_enabled(inst, false);
            dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, false);
            dma_channel_abort(inst->dma_channel);
            dma_irqn_acknowledge_channel(inst->dma_irq, inst->dma_channel);
            if (inst->playing_buffer) {
                give_audio_buffer(inst->consumer_pool, inst->playing_buffer);
                inst->playing_buffer = NULL;
            }
            dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, true);
            active[active_count++] = inst;
        }

        pio_sm_set_clkdiv_int_frac(inst->pio, inst->pio_sm,
                                    divider >> 8u, divider & 0xffu);
        inst->freq = sample_freq;
        all_sm_mask |= (1u << inst->pio_sm);
        pio = inst->pio;
    }

    // Reset clkdiv phase for ALL SMs (including disabled ones) so they're
    // phase-aligned when later re-enabled. Without this, a disabled SM's
    // divider accumulator drifts and it starts misaligned.
    if (pio && all_sm_mask) {
        pio_clkdiv_restart_sm_mask(pio, all_sm_mask);
    }

    // Restart previously enabled SMs in sync
    if (active_count > 0 && pio) {
        audio_i2s_enable_sync(active, active_count);
    }

    printf("I2S rate change: all %d instances updated to %d Hz\n",
           i2s_instance_count, (int)sample_freq);
}

// ---------------------------------------------------------------------------
// Master election query
// ---------------------------------------------------------------------------

int8_t audio_i2s_get_clock_master_index(void) {
    return i2s_clock_master_index;
}

// ---------------------------------------------------------------------------
// Clock-domain accessors
//
// Today the clock domain is folded into whichever TX instance owns the
// audio_i2s_clkout master program. These accessors derive the BCK/LRCLK/
// sample_freq view from that instance so callers (e.g. the I2S input
// subsystem) can observe BCK/LRCLK without reaching into TX-specific state.
// ---------------------------------------------------------------------------

bool audio_i2s_clock_domain_is_active(void) {
    if (i2s_clkout_only_active_flag) return true;
    return i2s_clock_master_index >= 0
        && (uint)i2s_clock_master_index < i2s_instance_count;
}

audio_i2s_clock_mode_t audio_i2s_clock_domain_mode(void) {
    // Only master mode exists today; slave mode lands with the I2S slave
    // input/output work and will be sourced from clock-domain config state.
    return AUDIO_I2S_CLOCK_MODE_MASTER;
}

uint8_t audio_i2s_clock_domain_bck_pin(void) {
    if (i2s_clkout_only_active_flag) return i2s_clkout_only_bck_pin;
    if (i2s_clock_master_index < 0) return 0xFFu;
    if ((uint)i2s_clock_master_index >= i2s_instance_count) return 0xFFu;
    return i2s_instances[i2s_clock_master_index]->clock_pin_base;
}

uint8_t audio_i2s_clock_domain_lrclk_pin(void) {
    uint8_t bck = audio_i2s_clock_domain_bck_pin();
    return bck == 0xFFu ? 0xFFu : (uint8_t)(bck + 1u);
}

uint32_t audio_i2s_clock_domain_sample_freq(void) {
    if (i2s_clkout_only_active_flag) return i2s_clkout_only_freq;
    if (i2s_clock_master_index < 0) return 0u;
    if ((uint)i2s_clock_master_index >= i2s_instance_count) return 0u;
    return i2s_instances[i2s_clock_master_index]->freq;
}

// ===========================================================================
// Clock domain configuration + bulk-change transactions
// ===========================================================================

void audio_i2s_clock_domain_configure(uint8_t bck_pin,
                                       uint8_t phantom_pio_idx,
                                       uint8_t phantom_sm) {
    // Validate parameters at the API boundary so misconfiguration surfaces
    // immediately rather than at the next phantom install (which can be
    // far from the call site, e.g. on input source change).
    if (phantom_pio_idx >= NUM_PIOS) {
        panic("audio_i2s_clock_domain_configure: phantom_pio_idx %u >= NUM_PIOS",
              (uint)phantom_pio_idx);
    }
    if (phantom_sm >= 4) {
        panic("audio_i2s_clock_domain_configure: phantom_sm %u >= 4",
              (uint)phantom_sm);
    }
    i2s_cd_bck_pin = bck_pin;
    i2s_cd_phantom_pio_idx = phantom_pio_idx;
    i2s_cd_phantom_sm = phantom_sm;
}

void audio_i2s_clock_domain_begin_transaction(void) {
    i2s_transaction_depth++;
}

void audio_i2s_clock_domain_commit_transaction(void) {
    if (i2s_transaction_depth == 0) return;  // unbalanced — no-op
    i2s_transaction_depth--;
    if (i2s_transaction_depth == 0 && i2s_deferred_election) {
        i2s_deferred_election = false;
        election_apply();
    }
}

// ===========================================================================
// Election internals — run after every TX/RX setup/teardown (or at commit)
// to assign master/slave roles and manage the phantom SM.
// ===========================================================================

// Reinit a registered TX instance's SM with the master program (clkout —
// drives BCK/LRCLK + first-slot data). Restores the divider; leaves SM
// disabled. Caller is responsible for re-enabling.
static void reinit_tx_as_master(audio_i2s_instance_t *inst) {
    uint pio_idx = pio_get_index(inst->pio);

    // Ensure clock pins are PIO-muxed (idempotent).
    pio_gpio_init(inst->pio, inst->clock_pin_base);
    pio_gpio_init(inst->pio, inst->clock_pin_base + 1);

    if (i2s_pio_program_offset[pio_idx] < 0) {
        i2s_pio_program_offset[pio_idx] =
            pio_add_program(inst->pio, &audio_i2s_clkout_program);
    }
    uint offset = (uint)i2s_pio_program_offset[pio_idx];
    audio_i2s_clkout_program_init(inst->pio, inst->pio_sm, offset,
                                   inst->data_pin, inst->clock_pin_base);
    inst->clock_master = true;

    // Restore divider (pio_sm_init resets it)
    if (inst->freq != 0) {
        uint32_t div = i2s_compute_divider(inst->freq);
        pio_sm_set_clkdiv_int_frac(inst->pio, inst->pio_sm,
                                    div >> 8u, div & 0xffu);
    }
}

// Reinit a registered TX instance's SM with the slave program (dataout —
// data only, observes BCK/LRCLK from the master via cycle-identical
// instruction cadence + sync start). Restores the divider; leaves SM
// disabled.
static void reinit_tx_as_slave(audio_i2s_instance_t *inst) {
    uint pio_idx = pio_get_index(inst->pio);

    if (i2s_slave_pio_program_offset[pio_idx] < 0) {
        i2s_slave_pio_program_offset[pio_idx] =
            pio_add_program(inst->pio, &audio_i2s_dataout_program);
    }
    uint offset = (uint)i2s_slave_pio_program_offset[pio_idx];
    audio_i2s_dataout_program_init(inst->pio, inst->pio_sm, offset,
                                     inst->data_pin);
    inst->clock_master = false;

    if (inst->freq != 0) {
        uint32_t div = i2s_compute_divider(inst->freq);
        pio_sm_set_clkdiv_int_frac(inst->pio, inst->pio_sm,
                                    div >> 8u, div & 0xffu);
    }
}

// Disable an enabled TX SM and unwind its DMA + IRQ refcount so the
// election can reinit its program. The instance is marked disabled.
// Phase 5 of election_apply re-enables (in sync).
static void election_quiesce_tx(audio_i2s_instance_t *inst) {
    if (!inst->enabled) return;
    pio_sm_set_enabled(inst->pio, inst->pio_sm, false);
    dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, false);
    dma_channel_abort(inst->dma_channel);
    if (inst->playing_buffer) {
        give_audio_buffer(inst->consumer_pool, inst->playing_buffer);
        inst->playing_buffer = NULL;
    }
    dma_irqn_acknowledge_channel(inst->dma_irq, inst->dma_channel);
    dma_irqn_set_channel_enabled(inst->dma_irq, inst->dma_channel, true);
    if (--i2s_irq_enable_count[inst->dma_irq] == 0) {
        irq_set_enabled(DMA_IRQ_0 + inst->dma_irq, false);
    }
    inst->enabled = false;
}

// Run the election and apply role/phantom changes. Sync-restarts any TX
// SMs whose role swap caused them to be disabled in this call.
static void election_apply(void) {
    // Snapshot which TX SMs are currently enabled (so we can restore them
    // after a role-swap reinit). Capacity-bounded by PICO_AUDIO_I2S_MAX_INSTANCES.
    bool was_enabled[PICO_AUDIO_I2S_MAX_INSTANCES] = {0};
    for (uint i = 0; i < i2s_instance_count; i++) {
        was_enabled[i] = i2s_instances[i]->enabled;
    }

    // Election rule:
    //   ≥1 TX:    lowest-index TX is master (combined clkout)
    //   0 TX, ≥1 RX:    install phantom (clkout-only SM)
    //   0 TX, 0 RX:    no clock domain
    int new_master_idx = (i2s_instance_count > 0) ? 0 : -1;
    bool want_phantom = (new_master_idx < 0) && (i2s_rx_instance_count > 0);

    // Determine target Fs (for divider computation on phantom and
    // newly-promoted master). Prefer a registered TX, then RX, then the
    // already-running phantom; default to 48 kHz if no source has yet
    // settled on a frequency.
    uint32_t fs = 0;
    if (new_master_idx >= 0 && i2s_instances[new_master_idx]->freq != 0) {
        fs = i2s_instances[new_master_idx]->freq;
    } else if (i2s_rx_instance_count > 0 && i2s_rx_instances[0]->freq != 0) {
        fs = i2s_rx_instances[0]->freq;
    } else if (i2s_clkout_only_active_flag) {
        fs = i2s_clkout_only_freq;
    }
    if (fs == 0) fs = 48000;

    // Defensive: if a teardown's array shift left master_index pointing past
    // the end (rare, but possible if the removed instance was master), clear it.
    if (i2s_clock_master_index >= 0 &&
        (uint)i2s_clock_master_index >= i2s_instance_count) {
        i2s_clock_master_index = -1;
    }

    // Phase 1: demote outgoing master if mismatch.
    if (i2s_clock_master_index >= 0 &&
        i2s_clock_master_index != new_master_idx) {
        audio_i2s_instance_t *m = i2s_instances[i2s_clock_master_index];
        election_quiesce_tx(m);
        reinit_tx_as_slave(m);
        i2s_clock_master_index = -1;
    }

    // Phase 2: promote new master (if any).
    if (new_master_idx >= 0 && i2s_clock_master_index != new_master_idx) {
        audio_i2s_instance_t *m = i2s_instances[new_master_idx];
        election_quiesce_tx(m);
        reinit_tx_as_master(m);
        i2s_clock_master_index = (int8_t)new_master_idx;
    }

    // Phase 3: phantom lifecycle.
    //   We always update Fs on a running phantom, but order install-vs-uninstall
    //   relative to TX promotion carefully. By this point Phase 2 has already
    //   reinit'd the new TX master if any (SM still disabled), so it's safe to
    //   uninstall the phantom — pin contention is impossible because the
    //   newly-promoted TX is not yet enabled.
    if (want_phantom && !i2s_clkout_only_active_flag) {
        if (i2s_cd_phantom_pio_idx != 0xFFu && i2s_cd_phantom_sm != 0xFFu &&
            i2s_cd_bck_pin != 0xFFu) {
            audio_i2s_clock_domain_clkout_only_start(
                i2s_cd_phantom_pio_idx, i2s_cd_phantom_sm,
                i2s_cd_bck_pin, fs);
        } else {
            // Programming error — caller registered an RX before configuring
            // the clock domain. Without phantom config we can't drive
            // BCK/LRCLK and the RX SM will stall forever at `wait gpio`.
            panic("I2S election: phantom requested but clock domain not configured "
                  "(call audio_i2s_clock_domain_configure first)");
        }
    } else if (!want_phantom && i2s_clkout_only_active_flag) {
        audio_i2s_clock_domain_clkout_only_stop();
    } else if (want_phantom && i2s_clkout_only_active_flag) {
        // Phantom already running — refresh Fs in case it changed.
        audio_i2s_clock_domain_clkout_only_set_frequency(fs);
    }

    // Phase 4: realign divider phase across ALL registered TX SMs on each
    // PIO, then sync-enable any SMs whose role swap left them disabled.
    //
    // The hard project constraint (CLAUDE.md: "Output slot alignment is
    // inviolable") requires that all SMs on the same PIO share the same
    // clkdiv counter phase. After reinit_tx_as_master/slave, the swapped
    // SM's clkdiv was reset by pio_sm_init; unaffected enabled SMs kept
    // their accumulated phase. A pio_clkdiv_restart on the union of all
    // TX SMs realigns them all together; the subsequent sync-enable then
    // starts the disabled (just-swapped) SMs at the same phase as the
    // already-running ones.
    //
    // Mirrors the pattern in audio_i2s_change_data_pin (lines further down
    // in this file — when a single TX changes its data pin, we restart
    // clkdiv on every TX SM on the same PIO block).
    uint32_t all_tx_mask[3] = {0, 0, 0};
    uint32_t restart_mask[3] = {0, 0, 0};
    bool any_restart = false;
    for (uint i = 0; i < i2s_instance_count; i++) {
        uint pio_idx = pio_get_index(i2s_instances[i]->pio);
        all_tx_mask[pio_idx] |= (1u << i2s_instances[i]->pio_sm);
        if (was_enabled[i] && !i2s_instances[i]->enabled) {
            restart_mask[pio_idx] |= (1u << i2s_instances[i]->pio_sm);
            any_restart = true;
        }
    }

    // Prime DMA + enable IRQ for each SM we are about to re-enable.
    if (any_restart) {
        for (uint i = 0; i < i2s_instance_count; i++) {
            if (was_enabled[i] && !i2s_instances[i]->enabled) {
                audio_i2s_instance_t *inst = i2s_instances[i];
                if (i2s_irq_enable_count[inst->dma_irq]++ == 0) {
                    irq_set_enabled(DMA_IRQ_0 + inst->dma_irq, true);
                }
                i2s_audio_start_dma_transfer(inst);
            }
        }
    }

    // Critical section: align all TX clkdivs on each PIO, then sync-enable
    // the role-swapped subset. Both must happen with interrupts disabled
    // so a DMA IRQ can't slip in between and observe a half-aligned state.
    if (all_tx_mask[0] || all_tx_mask[1] || all_tx_mask[2] || any_restart) {
        uint32_t save = save_and_disable_interrupts();
        for (uint p = 0; p < 3; p++) {
            if (all_tx_mask[p]) {
                pio_clkdiv_restart_sm_mask(i2s_pio_block_from_index(p),
                                            all_tx_mask[p]);
            }
        }
        if (any_restart) {
            for (uint p = 0; p < 3; p++) {
                if (restart_mask[p]) {
                    pio_enable_sm_mask_in_sync(i2s_pio_block_from_index(p),
                                                restart_mask[p]);
                }
            }
        }
        restore_interrupts(save);
    }

    if (any_restart) {
        for (uint i = 0; i < i2s_instance_count; i++) {
            if (was_enabled[i] && !i2s_instances[i]->enabled) {
                i2s_instances[i]->enabled = true;
            }
        }
    }
}

static void election_request(void) {
    if (i2s_transaction_depth > 0) {
        i2s_deferred_election = true;
        return;
    }
    election_apply();
}

// ---------------------------------------------------------------------------
// MCK generator functions — backed by CLK_GPOUTn (hardware clock generator)
//
// The selected GPIO determines which clk_gpout block is used (mapping is
// platform-specific; see GPIO_TO_GPOUT_CLOCK_HANDLE in hardware/clocks.h).
// On RP2040 only GPIO 21 (gpout0) is generally usable for DSPi (23-25 are
// reserved for power/LED).  RP2350 adds GPIO 13 / 15 to the GPOUT mapping.
//
// MCK frequency calculation:
//   MCK = sample_freq × multiplier
//   GPOUT divider (24.8) = sys_clk / MCK = sys_clk × 256 / (sample_freq × multiplier)
//   Compare to the old PIO route which used (sys_clk × 128 / ...) because the
//   toggle program produced one MCK cycle every 2 PIO cycles — GPOUT writes
//   the pin directly, so no factor of 2.
//
//   At 307.2 MHz, 48 kHz, 128×: 307200000 × 256 / (48000 × 128) = 12800 → 50.0  ← integer
//   At 307.2 MHz, 48 kHz, 256×: 307200000 × 256 / (48000 × 256) =  6400 → 25.0  ← integer (NEW vs PIO 12.5)
//   At 307.2 MHz, 96 kHz, 128×: 307200000 × 256 / (96000 × 128) =  6400 → 25.0  ← integer (NEW vs PIO 12.5)
//   At 307.2 MHz, 96 kHz, 256×: 307200000 × 256 / (96000 × 256) =  3200 → 12.5  ← still fractional
// ---------------------------------------------------------------------------

void audio_i2s_mck_setup(uint pin) {
    // Capture the pin only — actual hardware setup happens in
    // audio_i2s_mck_set_enabled(true) so the boot path can stay symmetric
    // with the disabled state at power-on.
    mck_pin_current = (uint8_t)pin;
    mck_running = false;
    mck_div_24_8 = 0u;
    printf("MCK setup: GPIO %u (CLK_GPOUT-driven; not yet running)\n", pin);
}

void audio_i2s_mck_set_enabled(bool enabled) {
    if (mck_pin_current == 0xFFu) return;

    if (enabled) {
        if (mck_running) return;
        if (mck_div_24_8 == 0u) {
            // No frequency configured yet — caller forgot to call
            // update_frequency before enabling.
            printf("MCK enable: no divider configured, refusing\n");
            return;
        }
        // clock_gpio_init_int_frac8 configures the AUXSRC + DIV registers,
        // sets the ENABLE bit, and routes the GPIO pad mux to the clk_gpout
        // function for that pin.  Source from clk_sys (= PLL_SYS post-divider)
        // for cleanest math against integer dividers.
        clock_gpio_init_int_frac8(mck_pin_current,
                                   CLOCKS_CLK_GPOUT0_CTRL_AUXSRC_VALUE_CLK_SYS,
                                   mck_div_24_8 >> 8u,
                                   (uint8_t)(mck_div_24_8 & 0xFFu));
        mck_running = true;
        printf("MCK enabled on GPIO %u\n", (uint)mck_pin_current);
    } else {
        if (!mck_running) return;
        // Disconnect pad mux so the pin drops to high-Z.  Leave the
        // CLK_GPOUTn divider register populated — re-enable will hit the
        // pad mux path again via clock_gpio_init_int_frac8.  The clock
        // generator continues to run internally; clearing its ENABLE bit
        // would save a few µA but currently no API to do that without
        // poking clocks_hw->clk[].ctrl directly.
        gpio_set_function(mck_pin_current, GPIO_FUNC_NULL);
        gpio_set_dir(mck_pin_current, GPIO_IN);
        mck_running = false;
        printf("MCK disabled on GPIO %u\n", (uint)mck_pin_current);
    }
}

void audio_i2s_mck_update_frequency(uint32_t sample_freq, uint32_t multiplier) {
    if (mck_pin_current == 0xFFu) return;

    // Defensive fallback for unexpected values.
    if (multiplier != 128 && multiplier != 256) {
        printf("MCK invalid multiplier %u, forcing 128\n", (uint)multiplier);
        multiplier = 128;
    }

    uint32_t sys_clk = clock_get_hz(clk_sys);

    // divider_24.8 = sys_clk × 256 / (sample_freq × multiplier)
    // Use 64-bit intermediate to avoid overflow.
    uint64_t num = (uint64_t)sys_clk * 256u;
    uint64_t den = (uint64_t)sample_freq * multiplier;
    uint32_t divider = (uint32_t)(num / den);

    printf("MCK divider 0x%x/256 (%u.%u) for %d Hz × %u = %u Hz (GPOUT)\n",
           (uint)divider, (uint)(divider >> 8), (uint)(divider & 0xff),
           (int)sample_freq, (uint)multiplier,
           (uint)(sample_freq * multiplier));

    assert(divider < 0x1000000);
    mck_div_24_8 = divider;

    if (mck_running) {
        // Update the divider register live.  The clk_gpout block accepts
        // glitchless divider changes — the output continues at the new
        // ratio after the next divider cycle.  Use clock_gpio_init_int_frac8
        // for simplicity (re-routes the pad mux too, idempotent).
        clock_gpio_init_int_frac8(mck_pin_current,
                                   CLOCKS_CLK_GPOUT0_CTRL_AUXSRC_VALUE_CLK_SYS,
                                   divider >> 8u,
                                   (uint8_t)(divider & 0xFFu));
    }
}

void audio_i2s_mck_change_pin(uint new_pin) {
    if (mck_pin_current == 0xFFu) return;
    assert(!mck_running);  // MCK must be disabled before changing pin

    // No hardware reconfiguration needed yet — the next set_enabled(true)
    // will route the new pin through the clk_gpout pad mux.  The library's
    // pin-validity checks (GPIO_TO_GPOUT_CLOCK_HANDLE) ensure the pin is
    // GPOUT-capable; vendor_commands.c enforces this before reaching us.
    mck_pin_current = (uint8_t)new_pin;
    printf("MCK pin changed to GPIO %u (takes effect on next enable)\n", new_pin);
}

uint8_t audio_i2s_mck_get_pin(void) {
    return mck_pin_current;
}

bool audio_i2s_mck_is_enabled(void) {
    return mck_running;
}

void audio_i2s_mck_set_divider(uint32_t div_24_8) {
    if (mck_pin_current == 0xFFu) return;
    assert(div_24_8 < 0x1000000);
    mck_div_24_8 = div_24_8;
    if (mck_running) {
        clock_gpio_init_int_frac8(mck_pin_current,
                                   CLOCKS_CLK_GPOUT0_CTRL_AUXSRC_VALUE_CLK_SYS,
                                   div_24_8 >> 8u,
                                   (uint8_t)(div_24_8 & 0xFFu));
    }
}

// ===========================================================================
// Clocks-only master — drives BCK/LRCLK without TX
// ===========================================================================
//
// Used when I2S input is selected and no I2S TX output is configured. The
// clkout-only program is cycle-identical to audio_i2s_clkout, so an RX SM
// running at the same divider stays bit-aligned.

bool audio_i2s_clock_domain_clkout_only_start(uint8_t pio_idx, uint8_t sm,
                                                uint8_t bck_pin, uint32_t fs) {
    if (i2s_clkout_only_active_flag) return true;  // Idempotent
    if (pio_idx >= NUM_PIOS) return false;
    if (sm >= 4) return false;
    if (i2s_clock_master_index >= 0) {
        // A TX master is currently driving BCK/LRCLK — refuse rather than fight.
        return false;
    }

    PIO pio = i2s_pio_block_from_index(pio_idx);
    pio_sm_claim(pio, sm);

    if (i2s_clkout_only_program_offset[pio_idx] < 0) {
        i2s_clkout_only_program_offset[pio_idx] =
            pio_add_program(pio, &audio_i2s_clkout_only_program);
    }
    uint offset = (uint)i2s_clkout_only_program_offset[pio_idx];
    audio_i2s_clkout_only_program_init(pio, sm, offset, bck_pin);

    // Apply divider — same as TX master (sys_clk * 2 / Fs).
    uint32_t divider = i2s_compute_divider(fs);
    pio_sm_set_clkdiv_int_frac(pio, sm, divider >> 8u, divider & 0xffu);

    // Reset divider phase counter so the phantom starts at a known phase.
    // pio_sm_set_clkdiv_int_frac sets the divider value but does not
    // reset the accumulator; without this, the phantom starts at an
    // arbitrary clkdiv phase carried over from any previous SM use of
    // this slot. Cross-PIO BCK/LRCLK observation by RX SMs tolerates this
    // (they self-sync on LRCLK low), but a future caller that wants
    // cross-PIO clkdiv alignment with the phantom needs phase 0.
    pio_clkdiv_restart_sm_mask(pio, 1u << sm);

    pio_sm_set_enabled(pio, sm, true);

    i2s_clkout_only_pio = pio;
    i2s_clkout_only_sm = (int)sm;
    i2s_clkout_only_bck_pin = bck_pin;
    i2s_clkout_only_freq = fs;
    i2s_clkout_only_active_flag = true;

    printf("I2S clkout-only: PIO%u SM%u BCK GPIO %u @ %u Hz\n",
           (uint)pio_idx, (uint)sm, (uint)bck_pin, (uint)fs);
    return true;
}

void audio_i2s_clock_domain_clkout_only_stop(void) {
    if (!i2s_clkout_only_active_flag) return;

    PIO   pio = i2s_clkout_only_pio;
    uint  sm  = (uint)i2s_clkout_only_sm;
    uint  pio_idx = pio_get_index(pio);
    uint8_t bck = i2s_clkout_only_bck_pin;

    pio_sm_set_enabled(pio, sm, false);

    // Pin handoff policy:
    //   - If a TX master is registered (i2s_clock_master_index >= 0), Phase 2
    //     of election_apply has already called pio_gpio_init on this PIO's
    //     clkout pins for the new TX master, taking over the pad mux. We
    //     must NOT release the pins here — that would un-mux the new TX
    //     master before its SM is enabled in Phase 4. Let the caller (Phase 4)
    //     drive the pins.
    //   - If no TX master is registered (last RX teardown, no TX), release
    //     BCK and LRCLK GPIOs to high-Z so the I2S clock domain is fully off.
    if (i2s_clock_master_index < 0 && bck != 0xFFu) {
        gpio_set_function(bck, GPIO_FUNC_NULL);
        gpio_set_dir(bck, GPIO_IN);
        gpio_set_function(bck + 1u, GPIO_FUNC_NULL);
        gpio_set_dir(bck + 1u, GPIO_IN);
    }

    pio_sm_unclaim(pio, sm);

    // Reclaim PIO instruction memory. Without this, repeated I2S input
    // start/stop cycles leak 8 instructions per cycle on the phantom's
    // PIO block — and that block is shared with SPDIF RX on both
    // platforms, so the next pio_add_program for SPDIF RX decoders would
    // panic. Mirror the pattern from pico_spdif_rx/spdif_rx.c:446.
    if (i2s_clkout_only_program_offset[pio_idx] >= 0) {
        pio_remove_program(pio, &audio_i2s_clkout_only_program,
                           (uint)i2s_clkout_only_program_offset[pio_idx]);
        i2s_clkout_only_program_offset[pio_idx] = -1;
    }

    i2s_clkout_only_pio = NULL;
    i2s_clkout_only_sm = -1;
    i2s_clkout_only_bck_pin = 0xFFu;
    i2s_clkout_only_freq = 0u;
    i2s_clkout_only_active_flag = false;

    printf("I2S clkout-only: stopped\n");
}

bool audio_i2s_clock_domain_clkout_only_is_active(void) {
    return i2s_clkout_only_active_flag;
}

void audio_i2s_clock_domain_clkout_only_set_frequency(uint32_t fs) {
    if (!i2s_clkout_only_active_flag) return;
    uint32_t divider = i2s_compute_divider(fs);
    pio_sm_set_clkdiv_int_frac(i2s_clkout_only_pio, (uint)i2s_clkout_only_sm,
                                divider >> 8u, divider & 0xffu);
    i2s_clkout_only_freq = fs;
}

// ===========================================================================
// I2S RX — capture DIN synchronously with the clock domain
// ===========================================================================

bool audio_i2s_rx_setup(audio_i2s_rx_instance_t *inst,
                         const audio_i2s_rx_config_t *config,
                         uint32_t sample_freq) {
    if (!inst || !config || !config->ring) return false;
    if (config->pio >= NUM_PIOS) return false;
    if (config->pio_sm >= 4) return false;
    if (config->slot_count != 2) return false;       // Phase 2: stereo only
    if (config->slot_width_bits != 32) return false; // Phase 2: 24-in-32 only

    // Ring size must be a power of 2 (DMA write-side ring constraint)
    uint32_t r = config->ring_size_words;
    if (r < 8u || (r & (r - 1u)) != 0u) return false;

    inst->pio = i2s_pio_block_from_index(config->pio);
    inst->pio_sm = config->pio_sm;
    inst->dma_channel = config->dma_channel;
    inst->din_pin = config->din_pin;
    inst->slot_count = config->slot_count;
    inst->slot_width_bits = config->slot_width_bits;
    inst->reserved = 0;
    inst->freq = sample_freq;
    inst->active = false;
    inst->ring = config->ring;
    inst->ring_size_words = r;
    inst->read_idx_words = 0u;

    // log2(ring_size_bytes) for DMA set_ring
    uint32_t ring_bytes = r * sizeof(uint32_t);
    uint8_t log2 = 0;
    while ((1u << log2) < ring_bytes) log2++;
    inst->ring_log2_bytes = log2;

    // The RX program observes BCK/LRCLK via absolute `wait gpio` patched
    // at `pio_sm_init` time. We need the BCK pin from either an active
    // TX master OR the clock domain config (used for the phantom). If
    // neither is available, the caller hasn't arranged clocks before
    // setting up RX — that's a programming error, not a recoverable
    // state, since the patched-in placeholder pins (0/1) would alias
    // to whatever GPIOs happen to live there (commonly UART) and silently
    // sample the wrong wire.
    uint8_t bck = audio_i2s_clock_domain_bck_pin();
    uint8_t lrclk = audio_i2s_clock_domain_lrclk_pin();
    if (bck == 0xFFu || lrclk == 0xFFu) {
        // Fall back to clock-domain config (set by audio_i2s_clock_domain_configure).
        // This handles the common Phase 2.5 boot path where the configure
        // call happens before any TX/RX setup, but no TX master is yet
        // registered when RX is set up first.
        if (i2s_cd_bck_pin == 0xFFu) {
            panic("audio_i2s_rx_setup: no clock domain configured; "
                  "call audio_i2s_clock_domain_configure first");
        }
        bck = i2s_cd_bck_pin;
        lrclk = (uint8_t)(i2s_cd_bck_pin + 1u);
    }

    pio_sm_claim(inst->pio, inst->pio_sm);

    if (i2s_datain_program_offset[config->pio] < 0) {
        i2s_datain_program_offset[config->pio] =
            pio_add_program(inst->pio, &audio_i2s_datain_program);
    }
    uint offset = (uint)i2s_datain_program_offset[config->pio];
    audio_i2s_datain_program_init(inst->pio, inst->pio_sm, offset,
                                   config->din_pin, bck, lrclk);

    // Apply divider matching the clock domain (sys_clk * 2 / Fs)
    uint32_t divider = i2s_compute_divider(sample_freq);
    pio_sm_set_clkdiv_int_frac(inst->pio, inst->pio_sm,
                                divider >> 8u, divider & 0xffu);

    // DMA: write-side ring into caller's buffer, DREQ from PIO RX FIFO,
    // huge transfer count so the channel runs effectively forever.
    dma_channel_claim(inst->dma_channel);
    dma_channel_config c = dma_channel_get_default_config(inst->dma_channel);
    channel_config_set_transfer_data_size(&c, DMA_SIZE_32);
    channel_config_set_read_increment(&c, false);
    channel_config_set_write_increment(&c, true);
    channel_config_set_dreq(&c, pio_get_dreq(inst->pio, inst->pio_sm, false));
    channel_config_set_ring(&c, true /*write side*/, inst->ring_log2_bytes);

    dma_channel_configure(inst->dma_channel, &c,
                          inst->ring,                                  // write
                          (const volatile void *)&inst->pio->rxf[inst->pio_sm],  // read
                          0xFFFFFFFFu,                                  // count
                          false);

    printf("I2S RX setup: SM%u DIN GPIO %u DMA %u ring %u words (log2 %u)\n",
           (uint)inst->pio_sm, (uint)inst->din_pin,
           (uint)inst->dma_channel, (uint)r, (uint)log2);

    // Register in the RX registry and trigger election. The election may
    // install the phantom (clkout-only SM) if no TX is currently registered.
    if (i2s_rx_instance_count < PICO_AUDIO_I2S_MAX_RX_INSTANCES) {
        i2s_rx_instances[i2s_rx_instance_count++] = inst;
    } else {
        printf("I2S RX setup: registry full (%u instances)\n",
               (uint)PICO_AUDIO_I2S_MAX_RX_INSTANCES);
    }
    election_request();

    return true;
}

void audio_i2s_rx_set_enabled(audio_i2s_rx_instance_t *inst, bool enabled) {
    if (!inst) return;
    if (enabled == inst->active) return;

    if (enabled) {
        // Re-patch absolute BCK/LRCLK pin operands in case they changed (e.g.
        // clkout-only started after rx_setup). Safe to re-patch when SM is
        // disabled.
        uint8_t bck = audio_i2s_clock_domain_bck_pin();
        uint8_t lrclk = audio_i2s_clock_domain_lrclk_pin();
        if (bck == 0xFFu || lrclk == 0xFFu) {
            // No clocks — refuse to enable. Caller forgot to start them.
            printf("I2S RX enable: no clock domain active, refusing\n");
            return;
        }
        uint pio_idx = pio_get_index(inst->pio);
        uint offset = (uint)i2s_datain_program_offset[pio_idx];
        inst->pio->instr_mem[offset + 0] = pio_encode_wait_gpio(false, lrclk);
        inst->pio->instr_mem[offset + 1] = pio_encode_wait_gpio(true,  bck);

        // Drain any stale RX FIFO content
        pio_sm_clear_fifos(inst->pio, inst->pio_sm);
        pio_sm_restart(inst->pio, inst->pio_sm);
        pio_sm_exec(inst->pio, inst->pio_sm,
                    pio_encode_jmp(offset + audio_i2s_datain_offset_entry_point));

        // Reset read pointer; the caller's first poll() will skip the first
        // (potentially partial) stereo frame.
        inst->read_idx_words = 0u;

        // Arm DMA at ring base
        dma_channel_set_write_addr(inst->dma_channel, inst->ring, false);
        dma_channel_set_trans_count(inst->dma_channel, 0xFFFFFFFFu, true);

        pio_sm_set_enabled(inst->pio, inst->pio_sm, true);
        inst->active = true;
    } else {
        pio_sm_set_enabled(inst->pio, inst->pio_sm, false);
        dma_channel_abort(inst->dma_channel);
        inst->active = false;
    }
}

void audio_i2s_rx_set_frequency(audio_i2s_rx_instance_t *inst, uint32_t fs) {
    if (!inst) return;
    uint32_t divider = i2s_compute_divider(fs);
    pio_sm_set_clkdiv_int_frac(inst->pio, inst->pio_sm,
                                divider >> 8u, divider & 0xffu);
    inst->freq = fs;
}

void audio_i2s_rx_teardown(audio_i2s_rx_instance_t *inst) {
    if (!inst) return;
    if (inst->active) {
        audio_i2s_rx_set_enabled(inst, false);
    }

    PIO  pio = inst->pio;
    uint pio_idx = pio_get_index(pio);

    dma_channel_unclaim(inst->dma_channel);
    pio_sm_unclaim(pio, inst->pio_sm);

    // Release DIN pin to high-Z
    gpio_set_function(inst->din_pin, GPIO_FUNC_NULL);
    gpio_set_dir(inst->din_pin, GPIO_IN);

    inst->ring = NULL;
    inst->ring_size_words = 0;
    inst->freq = 0;

    // Unregister from RX registry and trigger election. If this was the
    // last RX and no TX is registered, the election uninstalls the phantom.
    for (uint i = 0; i < i2s_rx_instance_count; i++) {
        if (i2s_rx_instances[i] == inst) {
            for (uint j = i; j < i2s_rx_instance_count - 1; j++) {
                i2s_rx_instances[j] = i2s_rx_instances[j + 1];
            }
            i2s_rx_instance_count--;
            break;
        }
    }

    // Reclaim PIO instruction memory if this was the last RX SM on this
    // PIO block. The RX program shares the PIO block with SPDIF RX; without
    // this, repeated input-source toggles leak 8 instructions per cycle
    // and SPDIF RX decoder loads will eventually panic the firmware.
    bool other_rx_on_same_pio = false;
    for (uint i = 0; i < i2s_rx_instance_count; i++) {
        if (i2s_rx_instances[i]->pio == pio) {
            other_rx_on_same_pio = true;
            break;
        }
    }
    if (!other_rx_on_same_pio && i2s_datain_program_offset[pio_idx] >= 0) {
        pio_remove_program(pio, &audio_i2s_datain_program,
                           (uint)i2s_datain_program_offset[pio_idx]);
        i2s_datain_program_offset[pio_idx] = -1;
    }

    election_request();
}

uint32_t audio_i2s_rx_get_write_idx(const audio_i2s_rx_instance_t *inst) {
    if (!inst || !inst->ring) return 0;
    uintptr_t base = (uintptr_t)inst->ring;
    uintptr_t cur  = (uintptr_t)dma_hw->ch[inst->dma_channel].write_addr;
    uint32_t off_bytes = (uint32_t)(cur - base);
    return (off_bytes >> 2) & (inst->ring_size_words - 1u);
}
