# Generates build_info.h with the git describe string and build date.
# Must run at BUILD time (cmake -P from a custom target), never at configure
# time; a configure-time stamp goes stale and silently reports an old hash.
# See Documentation/Features/firmware_versioning_spec.md, "Build provenance".
#
# Expected -D arguments:
#   REPO_DIR  - any directory inside the git checkout
#   OUT_FILE  - path of the header to generate

find_program(GIT_EXECUTABLE git)

set(DESCRIBE "unknown")
if(GIT_EXECUTABLE)
    execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${REPO_DIR}" describe --always --dirty --tags
        OUTPUT_VARIABLE _out
        OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET
        RESULT_VARIABLE _rc)
    if(_rc EQUAL 0 AND NOT _out STREQUAL "")
        set(DESCRIBE "${_out}")
    endif()
endif()

# The wire field is 48 bytes (47 chars + NUL). Clamp from the FRONT: the
# short hash and -dirty flag live at the end of a describe string and must
# survive; only the (recoverable) tag prefix may be lost.
string(LENGTH "${DESCRIBE}" _len)
if(_len GREATER 47)
    math(EXPR _start "${_len} - 47")
    string(SUBSTRING "${DESCRIBE}" ${_start} 47 DESCRIBE)
endif()

string(TIMESTAMP BUILD_DATE "%Y-%m-%d")

string(CONCAT _content
    "// Generated by scripts/gen_build_info.cmake on every build. Do not edit,\n"
    "// do not commit. Provenance for humans only; no software may compare it.\n"
    "#pragma once\n"
    "#define BUILD_GIT_DESCRIBE \"${DESCRIBE}\"\n"
    "#define BUILD_DATE \"${BUILD_DATE}\"\n")

# Write only on change so TUs including this header rebuild only when the
# hash, dirty state, or date actually moved.
set(_existing "")
if(EXISTS "${OUT_FILE}")
    file(READ "${OUT_FILE}" _existing)
endif()
if(NOT _content STREQUAL _existing)
    file(WRITE "${OUT_FILE}" "${_content}")
endif()
